// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/proto/network-service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetServerStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerStatusRequest) Reset() {
	*x = GetServerStatusRequest{}
	mi := &file_internal_proto_network_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerStatusRequest) ProtoMessage() {}

func (x *GetServerStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_network_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerStatusRequest.ProtoReflect.Descriptor instead.
func (*GetServerStatusRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_network_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetServerStatusRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type GetServerStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int64                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerStatusResponse) Reset() {
	*x = GetServerStatusResponse{}
	mi := &file_internal_proto_network_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerStatusResponse) ProtoMessage() {}

func (x *GetServerStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_network_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerStatusResponse.ProtoReflect.Descriptor instead.
func (*GetServerStatusResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_network_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetServerStatusResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type GetServerMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerMetadataRequest) Reset() {
	*x = GetServerMetadataRequest{}
	mi := &file_internal_proto_network_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerMetadataRequest) ProtoMessage() {}

func (x *GetServerMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_network_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetServerMetadataRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_network_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetServerMetadataRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

type GetServerMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Ping          int64                  `protobuf:"varint,2,opt,name=ping,proto3" json:"ping,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerMetadataResponse) Reset() {
	*x = GetServerMetadataResponse{}
	mi := &file_internal_proto_network_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerMetadataResponse) ProtoMessage() {}

func (x *GetServerMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_network_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerMetadataResponse.ProtoReflect.Descriptor instead.
func (*GetServerMetadataResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_network_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetServerMetadataResponse) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *GetServerMetadataResponse) GetPing() int64 {
	if x != nil {
		return x.Ping
	}
	return 0
}

var File_internal_proto_network_service_proto protoreflect.FileDescriptor

const file_internal_proto_network_service_proto_rawDesc = "" +
	"\n" +
	"$internal/proto/network-service.proto\x12\fuser_service\"(\n" +
	"\x16GetServerStatusRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\"1\n" +
	"\x17GetServerStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x03R\x06status\"7\n" +
	"\x18GetServerMetadataRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\"?\n" +
	"\x19GetServerMetadataResponse\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x12\n" +
	"\x04ping\x18\x02 \x01(\x03R\x04ping2\xd6\x01\n" +
	"\x0enetworkService\x12^\n" +
	"\x0fGetServerStatus\x12$.user_service.GetServerStatusRequest\x1a%.user_service.GetServerStatusResponse\x12d\n" +
	"\x11GetServerMetadata\x12&.user_service.GetServerMetadataRequest\x1a'.user_service.GetServerMetadataResponseB\x17Z\x15/internal/proto;protob\x06proto3"

var (
	file_internal_proto_network_service_proto_rawDescOnce sync.Once
	file_internal_proto_network_service_proto_rawDescData []byte
)

func file_internal_proto_network_service_proto_rawDescGZIP() []byte {
	file_internal_proto_network_service_proto_rawDescOnce.Do(func() {
		file_internal_proto_network_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_network_service_proto_rawDesc), len(file_internal_proto_network_service_proto_rawDesc)))
	})
	return file_internal_proto_network_service_proto_rawDescData
}

var file_internal_proto_network_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_proto_network_service_proto_goTypes = []any{
	(*GetServerStatusRequest)(nil),    // 0: user_service.GetServerStatusRequest
	(*GetServerStatusResponse)(nil),   // 1: user_service.GetServerStatusResponse
	(*GetServerMetadataRequest)(nil),  // 2: user_service.GetServerMetadataRequest
	(*GetServerMetadataResponse)(nil), // 3: user_service.GetServerMetadataResponse
}
var file_internal_proto_network_service_proto_depIdxs = []int32{
	0, // 0: user_service.networkService.GetServerStatus:input_type -> user_service.GetServerStatusRequest
	2, // 1: user_service.networkService.GetServerMetadata:input_type -> user_service.GetServerMetadataRequest
	1, // 2: user_service.networkService.GetServerStatus:output_type -> user_service.GetServerStatusResponse
	3, // 3: user_service.networkService.GetServerMetadata:output_type -> user_service.GetServerMetadataResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_network_service_proto_init() }
func file_internal_proto_network_service_proto_init() {
	if File_internal_proto_network_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_network_service_proto_rawDesc), len(file_internal_proto_network_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_network_service_proto_goTypes,
		DependencyIndexes: file_internal_proto_network_service_proto_depIdxs,
		MessageInfos:      file_internal_proto_network_service_proto_msgTypes,
	}.Build()
	File_internal_proto_network_service_proto = out.File
	file_internal_proto_network_service_proto_goTypes = nil
	file_internal_proto_network_service_proto_depIdxs = nil
}
