syntax = "proto3";

package host_metadata_service;

option go_package = "/internal/proto;proto";

message DisableBundleKeyRequest {
  string key = 1;
}

message DisableBundleKeyResponse {
  string Bundle = 1;
}

message RemoveBundleRequest {
  string UserID = 1;
  string Bundle = 2;
}

message RemoveBundleResponse {

}
service BundleService {
  rpc DisableBundleKey (DisableBundleKeyRequest) returns (DisableBundleKeyResponse);
  rpc RemoveBundle (RemoveBundleRequest) returns (RemoveBundleResponse);
}