// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v7.34.1
// source: internal/proto/bundle-service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DisableBundleKeyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *DisableBundleKeyRequest) Reset() {
	*x = DisableBundleKeyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_bundle_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DisableBundleKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableBundleKeyRequest) ProtoMessage() {}

func (x *DisableBundleKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_bundle_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableBundleKeyRequest.ProtoReflect.Descriptor instead.
func (*DisableBundleKeyRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_bundle_service_proto_rawDescGZIP(), []int{0}
}

func (x *DisableBundleKeyRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DisableBundleKeyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DisableBundleKeyResponse) Reset() {
	*x = DisableBundleKeyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_bundle_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DisableBundleKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableBundleKeyResponse) ProtoMessage() {}

func (x *DisableBundleKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_bundle_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableBundleKeyResponse.ProtoReflect.Descriptor instead.
func (*DisableBundleKeyResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_bundle_service_proto_rawDescGZIP(), []int{1}
}

type AddBundleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID string `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Bundle string `protobuf:"bytes,2,opt,name=Bundle,proto3" json:"Bundle,omitempty"`
}

func (x *AddBundleRequest) Reset() {
	*x = AddBundleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_bundle_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddBundleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBundleRequest) ProtoMessage() {}

func (x *AddBundleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_bundle_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBundleRequest.ProtoReflect.Descriptor instead.
func (*AddBundleRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_bundle_service_proto_rawDescGZIP(), []int{2}
}

func (x *AddBundleRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *AddBundleRequest) GetBundle() string {
	if x != nil {
		return x.Bundle
	}
	return ""
}

type AddBundleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddBundleResponse) Reset() {
	*x = AddBundleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_bundle_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddBundleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBundleResponse) ProtoMessage() {}

func (x *AddBundleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_bundle_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBundleResponse.ProtoReflect.Descriptor instead.
func (*AddBundleResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_bundle_service_proto_rawDescGZIP(), []int{3}
}

type RemoveBundleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID string `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Bundle string `protobuf:"bytes,2,opt,name=Bundle,proto3" json:"Bundle,omitempty"`
}

func (x *RemoveBundleRequest) Reset() {
	*x = RemoveBundleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_bundle_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveBundleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveBundleRequest) ProtoMessage() {}

func (x *RemoveBundleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_bundle_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveBundleRequest.ProtoReflect.Descriptor instead.
func (*RemoveBundleRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_bundle_service_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveBundleRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *RemoveBundleRequest) GetBundle() string {
	if x != nil {
		return x.Bundle
	}
	return ""
}

type RemoveBundleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RemoveBundleResponse) Reset() {
	*x = RemoveBundleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_bundle_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveBundleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveBundleResponse) ProtoMessage() {}

func (x *RemoveBundleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_bundle_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveBundleResponse.ProtoReflect.Descriptor instead.
func (*RemoveBundleResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_bundle_service_proto_rawDescGZIP(), []int{5}
}

var File_internal_proto_bundle_service_proto protoreflect.FileDescriptor

var file_internal_proto_bundle_service_proto_rawDesc = []byte{
	0x0a, 0x23, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x62, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x6d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x2b, 0x0a, 0x17,
	0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x42, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x4b, 0x65, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x1a, 0x0a, 0x18, 0x44, 0x69, 0x73,
	0x61, 0x62, 0x6c, 0x65, 0x42, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x42, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x42, 0x75, 0x6e, 0x64,
	0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x44, 0x12, 0x16, 0x0a, 0x06, 0x42, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x42, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x22, 0x13, 0x0a, 0x11, 0x41, 0x64, 0x64,
	0x42, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x45,
	0x0a, 0x13, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x42, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x16, 0x0a,
	0x06, 0x42, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x42,
	0x75, 0x6e, 0x64, 0x6c, 0x65, 0x22, 0x16, 0x0a, 0x14, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x42,
	0x75, 0x6e, 0x64, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xcd, 0x02,
	0x0a, 0x0d, 0x42, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x73, 0x0a, 0x10, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x42, 0x75, 0x6e, 0x64, 0x6c, 0x65,
	0x4b, 0x65, 0x79, 0x12, 0x2e, 0x2e, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x69, 0x73, 0x61,
	0x62, 0x6c, 0x65, 0x42, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x2f, 0x2e, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x69, 0x73, 0x61,
	0x62, 0x6c, 0x65, 0x42, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5e, 0x0a, 0x09, 0x41, 0x64, 0x64, 0x42, 0x75, 0x6e, 0x64, 0x6c,
	0x65, 0x12, 0x27, 0x2e, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x41, 0x64, 0x64, 0x42, 0x75, 0x6e,
	0x64, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x68, 0x6f, 0x73,
	0x74, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x41, 0x64, 0x64, 0x42, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x67, 0x0a, 0x0c, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x42, 0x75,
	0x6e, 0x64, 0x6c, 0x65, 0x12, 0x2a, 0x2e, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x6d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x42, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x2b, 0x2e, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x42,
	0x75, 0x6e, 0x64, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x17, 0x5a,
	0x15, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_proto_bundle_service_proto_rawDescOnce sync.Once
	file_internal_proto_bundle_service_proto_rawDescData = file_internal_proto_bundle_service_proto_rawDesc
)

func file_internal_proto_bundle_service_proto_rawDescGZIP() []byte {
	file_internal_proto_bundle_service_proto_rawDescOnce.Do(func() {
		file_internal_proto_bundle_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_proto_bundle_service_proto_rawDescData)
	})
	return file_internal_proto_bundle_service_proto_rawDescData
}

var file_internal_proto_bundle_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_proto_bundle_service_proto_goTypes = []interface{}{
	(*DisableBundleKeyRequest)(nil),  // 0: host_metadata_service.DisableBundleKeyRequest
	(*DisableBundleKeyResponse)(nil), // 1: host_metadata_service.DisableBundleKeyResponse
	(*AddBundleRequest)(nil),         // 2: host_metadata_service.AddBundleRequest
	(*AddBundleResponse)(nil),        // 3: host_metadata_service.AddBundleResponse
	(*RemoveBundleRequest)(nil),      // 4: host_metadata_service.RemoveBundleRequest
	(*RemoveBundleResponse)(nil),     // 5: host_metadata_service.RemoveBundleResponse
}
var file_internal_proto_bundle_service_proto_depIdxs = []int32{
	0, // 0: host_metadata_service.BundleService.DisableBundleKey:input_type -> host_metadata_service.DisableBundleKeyRequest
	2, // 1: host_metadata_service.BundleService.AddBundle:input_type -> host_metadata_service.AddBundleRequest
	4, // 2: host_metadata_service.BundleService.RemoveBundle:input_type -> host_metadata_service.RemoveBundleRequest
	1, // 3: host_metadata_service.BundleService.DisableBundleKey:output_type -> host_metadata_service.DisableBundleKeyResponse
	3, // 4: host_metadata_service.BundleService.AddBundle:output_type -> host_metadata_service.AddBundleResponse
	5, // 5: host_metadata_service.BundleService.RemoveBundle:output_type -> host_metadata_service.RemoveBundleResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_bundle_service_proto_init() }
func file_internal_proto_bundle_service_proto_init() {
	if File_internal_proto_bundle_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_proto_bundle_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DisableBundleKeyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_bundle_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DisableBundleKeyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_bundle_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddBundleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_bundle_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddBundleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_bundle_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveBundleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_bundle_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveBundleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_proto_bundle_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_bundle_service_proto_goTypes,
		DependencyIndexes: file_internal_proto_bundle_service_proto_depIdxs,
		MessageInfos:      file_internal_proto_bundle_service_proto_msgTypes,
	}.Build()
	File_internal_proto_bundle_service_proto = out.File
	file_internal_proto_bundle_service_proto_rawDesc = nil
	file_internal_proto_bundle_service_proto_goTypes = nil
	file_internal_proto_bundle_service_proto_depIdxs = nil
}
