// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v7.34.1
// source: internal/proto/bundle-service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	BundleService_DisableBundleKey_FullMethodName = "/host_metadata_service.BundleService/DisableBundleKey"
)

// BundleServiceClient is the client API for BundleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BundleServiceClient interface {
	DisableBundleKey(ctx context.Context, in *DisableBundleKeyRequest, opts ...grpc.CallOption) (*DisableBundleKeyResponse, error)
}

type bundleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBundleServiceClient(cc grpc.ClientConnInterface) BundleServiceClient {
	return &bundleServiceClient{cc}
}

func (c *bundleServiceClient) DisableBundleKey(ctx context.Context, in *DisableBundleKeyRequest, opts ...grpc.CallOption) (*DisableBundleKeyResponse, error) {
	out := new(DisableBundleKeyResponse)
	err := c.cc.Invoke(ctx, BundleService_DisableBundleKey_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BundleServiceServer is the server API for BundleService service.
// All implementations must embed UnimplementedBundleServiceServer
// for forward compatibility
type BundleServiceServer interface {
	DisableBundleKey(context.Context, *DisableBundleKeyRequest) (*DisableBundleKeyResponse, error)
	mustEmbedUnimplementedBundleServiceServer()
}

// UnimplementedBundleServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBundleServiceServer struct {
}

func (UnimplementedBundleServiceServer) DisableBundleKey(context.Context, *DisableBundleKeyRequest) (*DisableBundleKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisableBundleKey not implemented")
}
func (UnimplementedBundleServiceServer) mustEmbedUnimplementedBundleServiceServer() {}

// UnsafeBundleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BundleServiceServer will
// result in compilation errors.
type UnsafeBundleServiceServer interface {
	mustEmbedUnimplementedBundleServiceServer()
}

func RegisterBundleServiceServer(s grpc.ServiceRegistrar, srv BundleServiceServer) {
	s.RegisterService(&BundleService_ServiceDesc, srv)
}

func _BundleService_DisableBundleKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisableBundleKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BundleServiceServer).DisableBundleKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BundleService_DisableBundleKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BundleServiceServer).DisableBundleKey(ctx, req.(*DisableBundleKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BundleService_ServiceDesc is the grpc.ServiceDesc for BundleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BundleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "host_metadata_service.BundleService",
	HandlerType: (*BundleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DisableBundleKey",
			Handler:    _BundleService_DisableBundleKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/proto/bundle-service.proto",
}
