// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: hub/services/host-metadata-service/internal/proto/host-metadata-service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateHostServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ram           string                 `protobuf:"bytes,1,opt,name=ram,proto3" json:"ram,omitempty"`
	Cores         string                 `protobuf:"bytes,2,opt,name=cores,proto3" json:"cores,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHostServerRequest) Reset() {
	*x = CreateHostServerRequest{}
	mi := &file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHostServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHostServerRequest) ProtoMessage() {}

func (x *CreateHostServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHostServerRequest.ProtoReflect.Descriptor instead.
func (*CreateHostServerRequest) Descriptor() ([]byte, []int) {
	return file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateHostServerRequest) GetRam() string {
	if x != nil {
		return x.Ram
	}
	return ""
}

func (x *CreateHostServerRequest) GetCores() string {
	if x != nil {
		return x.Cores
	}
	return ""
}

type CreateHostServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostServerId  string                 `protobuf:"bytes,1,opt,name=host_server_id,json=hostServerId,proto3" json:"host_server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHostServerResponse) Reset() {
	*x = CreateHostServerResponse{}
	mi := &file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHostServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHostServerResponse) ProtoMessage() {}

func (x *CreateHostServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHostServerResponse.ProtoReflect.Descriptor instead.
func (*CreateHostServerResponse) Descriptor() ([]byte, []int) {
	return file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateHostServerResponse) GetHostServerId() string {
	if x != nil {
		return x.HostServerId
	}
	return ""
}

type DeleteHostServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostServerId  string                 `protobuf:"bytes,1,opt,name=host_server_id,json=hostServerId,proto3" json:"host_server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteHostServerRequest) Reset() {
	*x = DeleteHostServerRequest{}
	mi := &file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteHostServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHostServerRequest) ProtoMessage() {}

func (x *DeleteHostServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHostServerRequest.ProtoReflect.Descriptor instead.
func (*DeleteHostServerRequest) Descriptor() ([]byte, []int) {
	return file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteHostServerRequest) GetHostServerId() string {
	if x != nil {
		return x.HostServerId
	}
	return ""
}

type DeleteHostServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteHostServerResponse) Reset() {
	*x = DeleteHostServerResponse{}
	mi := &file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteHostServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHostServerResponse) ProtoMessage() {}

func (x *DeleteHostServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHostServerResponse.ProtoReflect.Descriptor instead.
func (*DeleteHostServerResponse) Descriptor() ([]byte, []int) {
	return file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_rawDescGZIP(), []int{3}
}

type GetAllHostServersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllHostServersRequest) Reset() {
	*x = GetAllHostServersRequest{}
	mi := &file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllHostServersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllHostServersRequest) ProtoMessage() {}

func (x *GetAllHostServersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllHostServersRequest.ProtoReflect.Descriptor instead.
func (*GetAllHostServersRequest) Descriptor() ([]byte, []int) {
	return file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_rawDescGZIP(), []int{4}
}

type HostServer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Servers       map[string]int32       `protobuf:"bytes,2,rep,name=servers,proto3" json:"servers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Ram           string                 `protobuf:"bytes,3,opt,name=ram,proto3" json:"ram,omitempty"`
	Cores         string                 `protobuf:"bytes,4,opt,name=cores,proto3" json:"cores,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostServer) Reset() {
	*x = HostServer{}
	mi := &file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostServer) ProtoMessage() {}

func (x *HostServer) ProtoReflect() protoreflect.Message {
	mi := &file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostServer.ProtoReflect.Descriptor instead.
func (*HostServer) Descriptor() ([]byte, []int) {
	return file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_rawDescGZIP(), []int{5}
}

func (x *HostServer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HostServer) GetServers() map[string]int32 {
	if x != nil {
		return x.Servers
	}
	return nil
}

func (x *HostServer) GetRam() string {
	if x != nil {
		return x.Ram
	}
	return ""
}

func (x *HostServer) GetCores() string {
	if x != nil {
		return x.Cores
	}
	return ""
}

func (x *HostServer) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetAllHostServersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hosts         []*HostServer          `protobuf:"bytes,1,rep,name=hosts,proto3" json:"hosts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllHostServersResponse) Reset() {
	*x = GetAllHostServersResponse{}
	mi := &file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllHostServersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllHostServersResponse) ProtoMessage() {}

func (x *GetAllHostServersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllHostServersResponse.ProtoReflect.Descriptor instead.
func (*GetAllHostServersResponse) Descriptor() ([]byte, []int) {
	return file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetAllHostServersResponse) GetHosts() []*HostServer {
	if x != nil {
		return x.Hosts
	}
	return nil
}

type AddServerToHostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostServerId  string                 `protobuf:"bytes,1,opt,name=host_server_id,json=hostServerId,proto3" json:"host_server_id,omitempty"`
	ServerId      string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddServerToHostRequest) Reset() {
	*x = AddServerToHostRequest{}
	mi := &file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddServerToHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddServerToHostRequest) ProtoMessage() {}

func (x *AddServerToHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddServerToHostRequest.ProtoReflect.Descriptor instead.
func (*AddServerToHostRequest) Descriptor() ([]byte, []int) {
	return file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_rawDescGZIP(), []int{7}
}

func (x *AddServerToHostRequest) GetHostServerId() string {
	if x != nil {
		return x.HostServerId
	}
	return ""
}

func (x *AddServerToHostRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

type AddServerToHostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddServerToHostResponse) Reset() {
	*x = AddServerToHostResponse{}
	mi := &file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddServerToHostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddServerToHostResponse) ProtoMessage() {}

func (x *AddServerToHostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddServerToHostResponse.ProtoReflect.Descriptor instead.
func (*AddServerToHostResponse) Descriptor() ([]byte, []int) {
	return file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_rawDescGZIP(), []int{8}
}

type RemoveServerFromHostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostServerId  string                 `protobuf:"bytes,1,opt,name=host_server_id,json=hostServerId,proto3" json:"host_server_id,omitempty"`
	ServerId      string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveServerFromHostRequest) Reset() {
	*x = RemoveServerFromHostRequest{}
	mi := &file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveServerFromHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveServerFromHostRequest) ProtoMessage() {}

func (x *RemoveServerFromHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveServerFromHostRequest.ProtoReflect.Descriptor instead.
func (*RemoveServerFromHostRequest) Descriptor() ([]byte, []int) {
	return file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_rawDescGZIP(), []int{9}
}

func (x *RemoveServerFromHostRequest) GetHostServerId() string {
	if x != nil {
		return x.HostServerId
	}
	return ""
}

func (x *RemoveServerFromHostRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

type RemoveServerFromHostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveServerFromHostResponse) Reset() {
	*x = RemoveServerFromHostResponse{}
	mi := &file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveServerFromHostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveServerFromHostResponse) ProtoMessage() {}

func (x *RemoveServerFromHostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveServerFromHostResponse.ProtoReflect.Descriptor instead.
func (*RemoveServerFromHostResponse) Descriptor() ([]byte, []int) {
	return file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_rawDescGZIP(), []int{10}
}

type AddPortToServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostServerId  string                 `protobuf:"bytes,1,opt,name=host_server_id,json=hostServerId,proto3" json:"host_server_id,omitempty"`
	ServerId      string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPortToServerRequest) Reset() {
	*x = AddPortToServerRequest{}
	mi := &file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPortToServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPortToServerRequest) ProtoMessage() {}

func (x *AddPortToServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPortToServerRequest.ProtoReflect.Descriptor instead.
func (*AddPortToServerRequest) Descriptor() ([]byte, []int) {
	return file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_rawDescGZIP(), []int{11}
}

func (x *AddPortToServerRequest) GetHostServerId() string {
	if x != nil {
		return x.HostServerId
	}
	return ""
}

func (x *AddPortToServerRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *AddPortToServerRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type AddPortToServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPortToServerResponse) Reset() {
	*x = AddPortToServerResponse{}
	mi := &file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPortToServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPortToServerResponse) ProtoMessage() {}

func (x *AddPortToServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPortToServerResponse.ProtoReflect.Descriptor instead.
func (*AddPortToServerResponse) Descriptor() ([]byte, []int) {
	return file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_rawDescGZIP(), []int{12}
}

type GetRAMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostServerId  string                 `protobuf:"bytes,1,opt,name=host_server_id,json=hostServerId,proto3" json:"host_server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRAMRequest) Reset() {
	*x = GetRAMRequest{}
	mi := &file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRAMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRAMRequest) ProtoMessage() {}

func (x *GetRAMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRAMRequest.ProtoReflect.Descriptor instead.
func (*GetRAMRequest) Descriptor() ([]byte, []int) {
	return file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_rawDescGZIP(), []int{13}
}

func (x *GetRAMRequest) GetHostServerId() string {
	if x != nil {
		return x.HostServerId
	}
	return ""
}

type GetRAMResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ram           string                 `protobuf:"bytes,1,opt,name=ram,proto3" json:"ram,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRAMResponse) Reset() {
	*x = GetRAMResponse{}
	mi := &file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRAMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRAMResponse) ProtoMessage() {}

func (x *GetRAMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRAMResponse.ProtoReflect.Descriptor instead.
func (*GetRAMResponse) Descriptor() ([]byte, []int) {
	return file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_rawDescGZIP(), []int{14}
}

func (x *GetRAMResponse) GetRam() string {
	if x != nil {
		return x.Ram
	}
	return ""
}

type GetCoresRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostServerId  string                 `protobuf:"bytes,1,opt,name=host_server_id,json=hostServerId,proto3" json:"host_server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCoresRequest) Reset() {
	*x = GetCoresRequest{}
	mi := &file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCoresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoresRequest) ProtoMessage() {}

func (x *GetCoresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoresRequest.ProtoReflect.Descriptor instead.
func (*GetCoresRequest) Descriptor() ([]byte, []int) {
	return file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_rawDescGZIP(), []int{15}
}

func (x *GetCoresRequest) GetHostServerId() string {
	if x != nil {
		return x.HostServerId
	}
	return ""
}

type GetCoresResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cores         string                 `protobuf:"bytes,1,opt,name=cores,proto3" json:"cores,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCoresResponse) Reset() {
	*x = GetCoresResponse{}
	mi := &file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCoresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoresResponse) ProtoMessage() {}

func (x *GetCoresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoresResponse.ProtoReflect.Descriptor instead.
func (*GetCoresResponse) Descriptor() ([]byte, []int) {
	return file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_rawDescGZIP(), []int{16}
}

func (x *GetCoresResponse) GetCores() string {
	if x != nil {
		return x.Cores
	}
	return ""
}

type SubtractRAMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostServerId  string                 `protobuf:"bytes,1,opt,name=host_server_id,json=hostServerId,proto3" json:"host_server_id,omitempty"`
	Ram           string                 `protobuf:"bytes,2,opt,name=ram,proto3" json:"ram,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubtractRAMRequest) Reset() {
	*x = SubtractRAMRequest{}
	mi := &file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubtractRAMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubtractRAMRequest) ProtoMessage() {}

func (x *SubtractRAMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubtractRAMRequest.ProtoReflect.Descriptor instead.
func (*SubtractRAMRequest) Descriptor() ([]byte, []int) {
	return file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_rawDescGZIP(), []int{17}
}

func (x *SubtractRAMRequest) GetHostServerId() string {
	if x != nil {
		return x.HostServerId
	}
	return ""
}

func (x *SubtractRAMRequest) GetRam() string {
	if x != nil {
		return x.Ram
	}
	return ""
}

type SubtractRAMResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubtractRAMResponse) Reset() {
	*x = SubtractRAMResponse{}
	mi := &file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubtractRAMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubtractRAMResponse) ProtoMessage() {}

func (x *SubtractRAMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubtractRAMResponse.ProtoReflect.Descriptor instead.
func (*SubtractRAMResponse) Descriptor() ([]byte, []int) {
	return file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_rawDescGZIP(), []int{18}
}

type SubtractCoresRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostServerId  string                 `protobuf:"bytes,1,opt,name=host_server_id,json=hostServerId,proto3" json:"host_server_id,omitempty"`
	Cores         string                 `protobuf:"bytes,2,opt,name=cores,proto3" json:"cores,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubtractCoresRequest) Reset() {
	*x = SubtractCoresRequest{}
	mi := &file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubtractCoresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubtractCoresRequest) ProtoMessage() {}

func (x *SubtractCoresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubtractCoresRequest.ProtoReflect.Descriptor instead.
func (*SubtractCoresRequest) Descriptor() ([]byte, []int) {
	return file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_rawDescGZIP(), []int{19}
}

func (x *SubtractCoresRequest) GetHostServerId() string {
	if x != nil {
		return x.HostServerId
	}
	return ""
}

func (x *SubtractCoresRequest) GetCores() string {
	if x != nil {
		return x.Cores
	}
	return ""
}

type SubtractCoresResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubtractCoresResponse) Reset() {
	*x = SubtractCoresResponse{}
	mi := &file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubtractCoresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubtractCoresResponse) ProtoMessage() {}

func (x *SubtractCoresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubtractCoresResponse.ProtoReflect.Descriptor instead.
func (*SubtractCoresResponse) Descriptor() ([]byte, []int) {
	return file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_rawDescGZIP(), []int{20}
}

var File_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto protoreflect.FileDescriptor

const file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_rawDesc = "" +
	"\n" +
	"Mhub/services/host-metadata-service/internal/proto/host-metadata-service.proto\x12\x15host_metadata_service\"A\n" +
	"\x17CreateHostServerRequest\x12\x10\n" +
	"\x03ram\x18\x01 \x01(\tR\x03ram\x12\x14\n" +
	"\x05cores\x18\x02 \x01(\tR\x05cores\"@\n" +
	"\x18CreateHostServerResponse\x12$\n" +
	"\x0ehost_server_id\x18\x01 \x01(\tR\fhostServerId\"?\n" +
	"\x17DeleteHostServerRequest\x12$\n" +
	"\x0ehost_server_id\x18\x01 \x01(\tR\fhostServerId\"\x1a\n" +
	"\x18DeleteHostServerResponse\"\x1a\n" +
	"\x18GetAllHostServersRequest\"\xe9\x01\n" +
	"\n" +
	"HostServer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12H\n" +
	"\aservers\x18\x02 \x03(\v2..host_metadata_service.HostServer.ServersEntryR\aservers\x12\x10\n" +
	"\x03ram\x18\x03 \x01(\tR\x03ram\x12\x14\n" +
	"\x05cores\x18\x04 \x01(\tR\x05cores\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x1a:\n" +
	"\fServersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"T\n" +
	"\x19GetAllHostServersResponse\x127\n" +
	"\x05hosts\x18\x01 \x03(\v2!.host_metadata_service.HostServerR\x05hosts\"[\n" +
	"\x16AddServerToHostRequest\x12$\n" +
	"\x0ehost_server_id\x18\x01 \x01(\tR\fhostServerId\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\"\x19\n" +
	"\x17AddServerToHostResponse\"`\n" +
	"\x1bRemoveServerFromHostRequest\x12$\n" +
	"\x0ehost_server_id\x18\x01 \x01(\tR\fhostServerId\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\"\x1e\n" +
	"\x1cRemoveServerFromHostResponse\"o\n" +
	"\x16AddPortToServerRequest\x12$\n" +
	"\x0ehost_server_id\x18\x01 \x01(\tR\fhostServerId\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\"\x19\n" +
	"\x17AddPortToServerResponse\"5\n" +
	"\rGetRAMRequest\x12$\n" +
	"\x0ehost_server_id\x18\x01 \x01(\tR\fhostServerId\"\"\n" +
	"\x0eGetRAMResponse\x12\x10\n" +
	"\x03ram\x18\x01 \x01(\tR\x03ram\"7\n" +
	"\x0fGetCoresRequest\x12$\n" +
	"\x0ehost_server_id\x18\x01 \x01(\tR\fhostServerId\"(\n" +
	"\x10GetCoresResponse\x12\x14\n" +
	"\x05cores\x18\x01 \x01(\tR\x05cores\"L\n" +
	"\x12SubtractRAMRequest\x12$\n" +
	"\x0ehost_server_id\x18\x01 \x01(\tR\fhostServerId\x12\x10\n" +
	"\x03ram\x18\x02 \x01(\tR\x03ram\"\x15\n" +
	"\x13SubtractRAMResponse\"R\n" +
	"\x14SubtractCoresRequest\x12$\n" +
	"\x0ehost_server_id\x18\x01 \x01(\tR\fhostServerId\x12\x14\n" +
	"\x05cores\x18\x02 \x01(\tR\x05cores\"\x17\n" +
	"\x15SubtractCoresResponse2\xe2\b\n" +
	"\x13HostMetadataService\x12s\n" +
	"\x10CreateHostServer\x12..host_metadata_service.CreateHostServerRequest\x1a/.host_metadata_service.CreateHostServerResponse\x12s\n" +
	"\x10DeleteHostServer\x12..host_metadata_service.DeleteHostServerRequest\x1a/.host_metadata_service.DeleteHostServerResponse\x12v\n" +
	"\x11GetAllHostServers\x12/.host_metadata_service.GetAllHostServersRequest\x1a0.host_metadata_service.GetAllHostServersResponse\x12p\n" +
	"\x0fAddServerToHost\x12-.host_metadata_service.AddServerToHostRequest\x1a..host_metadata_service.AddServerToHostResponse\x12\x7f\n" +
	"\x14RemoveServerFromHost\x122.host_metadata_service.RemoveServerFromHostRequest\x1a3.host_metadata_service.RemoveServerFromHostResponse\x12p\n" +
	"\x0fAddPortToServer\x12-.host_metadata_service.AddPortToServerRequest\x1a..host_metadata_service.AddPortToServerResponse\x12U\n" +
	"\x06GetRAM\x12$.host_metadata_service.GetRAMRequest\x1a%.host_metadata_service.GetRAMResponse\x12[\n" +
	"\bGetCores\x12&.host_metadata_service.GetCoresRequest\x1a'.host_metadata_service.GetCoresResponse\x12d\n" +
	"\vSubtractRAM\x12).host_metadata_service.SubtractRAMRequest\x1a*.host_metadata_service.SubtractRAMResponse\x12j\n" +
	"\rSubtractCores\x12+.host_metadata_service.SubtractCoresRequest\x1a,.host_metadata_service.SubtractCoresResponseB\x17Z\x15/internal/proto;protob\x06proto3"

var (
	file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_rawDescOnce sync.Once
	file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_rawDescData []byte
)

func file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_rawDescGZIP() []byte {
	file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_rawDescOnce.Do(func() {
		file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_rawDesc), len(file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_rawDesc)))
	})
	return file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_rawDescData
}

var file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_goTypes = []any{
	(*CreateHostServerRequest)(nil),      // 0: host_metadata_service.CreateHostServerRequest
	(*CreateHostServerResponse)(nil),     // 1: host_metadata_service.CreateHostServerResponse
	(*DeleteHostServerRequest)(nil),      // 2: host_metadata_service.DeleteHostServerRequest
	(*DeleteHostServerResponse)(nil),     // 3: host_metadata_service.DeleteHostServerResponse
	(*GetAllHostServersRequest)(nil),     // 4: host_metadata_service.GetAllHostServersRequest
	(*HostServer)(nil),                   // 5: host_metadata_service.HostServer
	(*GetAllHostServersResponse)(nil),    // 6: host_metadata_service.GetAllHostServersResponse
	(*AddServerToHostRequest)(nil),       // 7: host_metadata_service.AddServerToHostRequest
	(*AddServerToHostResponse)(nil),      // 8: host_metadata_service.AddServerToHostResponse
	(*RemoveServerFromHostRequest)(nil),  // 9: host_metadata_service.RemoveServerFromHostRequest
	(*RemoveServerFromHostResponse)(nil), // 10: host_metadata_service.RemoveServerFromHostResponse
	(*AddPortToServerRequest)(nil),       // 11: host_metadata_service.AddPortToServerRequest
	(*AddPortToServerResponse)(nil),      // 12: host_metadata_service.AddPortToServerResponse
	(*GetRAMRequest)(nil),                // 13: host_metadata_service.GetRAMRequest
	(*GetRAMResponse)(nil),               // 14: host_metadata_service.GetRAMResponse
	(*GetCoresRequest)(nil),              // 15: host_metadata_service.GetCoresRequest
	(*GetCoresResponse)(nil),             // 16: host_metadata_service.GetCoresResponse
	(*SubtractRAMRequest)(nil),           // 17: host_metadata_service.SubtractRAMRequest
	(*SubtractRAMResponse)(nil),          // 18: host_metadata_service.SubtractRAMResponse
	(*SubtractCoresRequest)(nil),         // 19: host_metadata_service.SubtractCoresRequest
	(*SubtractCoresResponse)(nil),        // 20: host_metadata_service.SubtractCoresResponse
	nil,                                  // 21: host_metadata_service.HostServer.ServersEntry
}
var file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_depIdxs = []int32{
	21, // 0: host_metadata_service.HostServer.servers:type_name -> host_metadata_service.HostServer.ServersEntry
	5,  // 1: host_metadata_service.GetAllHostServersResponse.hosts:type_name -> host_metadata_service.HostServer
	0,  // 2: host_metadata_service.HostMetadataService.CreateHostServer:input_type -> host_metadata_service.CreateHostServerRequest
	2,  // 3: host_metadata_service.HostMetadataService.DeleteHostServer:input_type -> host_metadata_service.DeleteHostServerRequest
	4,  // 4: host_metadata_service.HostMetadataService.GetAllHostServers:input_type -> host_metadata_service.GetAllHostServersRequest
	7,  // 5: host_metadata_service.HostMetadataService.AddServerToHost:input_type -> host_metadata_service.AddServerToHostRequest
	9,  // 6: host_metadata_service.HostMetadataService.RemoveServerFromHost:input_type -> host_metadata_service.RemoveServerFromHostRequest
	11, // 7: host_metadata_service.HostMetadataService.AddPortToServer:input_type -> host_metadata_service.AddPortToServerRequest
	13, // 8: host_metadata_service.HostMetadataService.GetRAM:input_type -> host_metadata_service.GetRAMRequest
	15, // 9: host_metadata_service.HostMetadataService.GetCores:input_type -> host_metadata_service.GetCoresRequest
	17, // 10: host_metadata_service.HostMetadataService.SubtractRAM:input_type -> host_metadata_service.SubtractRAMRequest
	19, // 11: host_metadata_service.HostMetadataService.SubtractCores:input_type -> host_metadata_service.SubtractCoresRequest
	1,  // 12: host_metadata_service.HostMetadataService.CreateHostServer:output_type -> host_metadata_service.CreateHostServerResponse
	3,  // 13: host_metadata_service.HostMetadataService.DeleteHostServer:output_type -> host_metadata_service.DeleteHostServerResponse
	6,  // 14: host_metadata_service.HostMetadataService.GetAllHostServers:output_type -> host_metadata_service.GetAllHostServersResponse
	8,  // 15: host_metadata_service.HostMetadataService.AddServerToHost:output_type -> host_metadata_service.AddServerToHostResponse
	10, // 16: host_metadata_service.HostMetadataService.RemoveServerFromHost:output_type -> host_metadata_service.RemoveServerFromHostResponse
	12, // 17: host_metadata_service.HostMetadataService.AddPortToServer:output_type -> host_metadata_service.AddPortToServerResponse
	14, // 18: host_metadata_service.HostMetadataService.GetRAM:output_type -> host_metadata_service.GetRAMResponse
	16, // 19: host_metadata_service.HostMetadataService.GetCores:output_type -> host_metadata_service.GetCoresResponse
	18, // 20: host_metadata_service.HostMetadataService.SubtractRAM:output_type -> host_metadata_service.SubtractRAMResponse
	20, // 21: host_metadata_service.HostMetadataService.SubtractCores:output_type -> host_metadata_service.SubtractCoresResponse
	12, // [12:22] is the sub-list for method output_type
	2,  // [2:12] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() {
	file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_init()
}
func file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_init() {
	if File_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_rawDesc), len(file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_goTypes,
		DependencyIndexes: file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_depIdxs,
		MessageInfos:      file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_msgTypes,
	}.Build()
	File_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto = out.File
	file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_goTypes = nil
	file_hub_services_host_metadata_service_internal_proto_host_metadata_service_proto_depIdxs = nil
}
