syntax = "proto3";

package host_metadata_service;

option go_package = "/internal/proto;proto";

message CreateHostServerRequest {
  string ram = 1;
  string cores = 2;
}

message CreateHostServerResponse {
  string host_server_id = 1;
}

message DeleteHostServerRequest {
  string host_server_id = 1;
}

message DeleteHostServerResponse {
}

message GetAllHostServersRequest {
}

message HostServer {
  string id = 1;
  repeated string servers = 2;
  string created_at = 3;
}

message GetAllHostServersResponse {
  repeated HostServer hosts = 1;
}

message AddServerToHostRequest {
  string host_server_id = 1;
  string server_id = 2;
}

message AddServerToHostResponse {
}

message RemoveServerFromHostRequest {
  string host_server_id = 1;
  string server_id = 2;
}

message RemoveServerFromHostResponse {
}

message GetRAMRequest {
  string host_server_id = 1;
}

message GetRAMResponse {
  string ram = 1;
}

message GetCoresRequest {
  string host_server_id = 1;
}

message GetCoresResponse {
  string cores = 1;
}

message SubtractRAMRequest {
  string host_server_id = 1;
  string ram = 2;
}

message SubtractRAMResponse {
}

message SubtractCoresRequest {
  string host_server_id = 1;
  string cores = 2;
}

message SubtractCoresResponse {
}

service HostMetadataService {
  rpc CreateHostServer (CreateHostServerRequest) returns (CreateHostServerResponse);
  rpc DeleteHostServer (DeleteHostServerRequest) returns (DeleteHostServerResponse);
  rpc GetAllHostServers (GetAllHostServersRequest) returns (GetAllHostServersResponse);
  rpc AddServerToHost (AddServerToHostRequest) returns (AddServerToHostResponse);
  rpc RemoveServerFromHost (RemoveServerFromHostRequest) returns (RemoveServerFromHostResponse);
  rpc GetRAM (GetRAMRequest) returns (GetRAMResponse);
  rpc GetCores (GetCoresRequest) returns (GetCoresResponse);
  rpc SubtractRAM (SubtractRAMRequest) returns (SubtractRAMResponse);
  rpc SubtractCores (SubtractCoresRequest) returns (SubtractCoresResponse);
}
