// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/proto/host-metadata-service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateHostServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHostServerRequest) Reset() {
	*x = CreateHostServerRequest{}
	mi := &file_internal_proto_host_metadata_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHostServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHostServerRequest) ProtoMessage() {}

func (x *CreateHostServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_host_metadata_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHostServerRequest.ProtoReflect.Descriptor instead.
func (*CreateHostServerRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_host_metadata_service_proto_rawDescGZIP(), []int{0}
}

type CreateHostServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostServerId  string                 `protobuf:"bytes,1,opt,name=host_server_id,json=hostServerId,proto3" json:"host_server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHostServerResponse) Reset() {
	*x = CreateHostServerResponse{}
	mi := &file_internal_proto_host_metadata_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHostServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHostServerResponse) ProtoMessage() {}

func (x *CreateHostServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_host_metadata_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHostServerResponse.ProtoReflect.Descriptor instead.
func (*CreateHostServerResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_host_metadata_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateHostServerResponse) GetHostServerId() string {
	if x != nil {
		return x.HostServerId
	}
	return ""
}

type DeleteHostServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostServerId  string                 `protobuf:"bytes,1,opt,name=host_server_id,json=hostServerId,proto3" json:"host_server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteHostServerRequest) Reset() {
	*x = DeleteHostServerRequest{}
	mi := &file_internal_proto_host_metadata_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteHostServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHostServerRequest) ProtoMessage() {}

func (x *DeleteHostServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_host_metadata_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHostServerRequest.ProtoReflect.Descriptor instead.
func (*DeleteHostServerRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_host_metadata_service_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteHostServerRequest) GetHostServerId() string {
	if x != nil {
		return x.HostServerId
	}
	return ""
}

type DeleteHostServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteHostServerResponse) Reset() {
	*x = DeleteHostServerResponse{}
	mi := &file_internal_proto_host_metadata_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteHostServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHostServerResponse) ProtoMessage() {}

func (x *DeleteHostServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_host_metadata_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHostServerResponse.ProtoReflect.Descriptor instead.
func (*DeleteHostServerResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_host_metadata_service_proto_rawDescGZIP(), []int{3}
}

type GetAllHostServersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllHostServersRequest) Reset() {
	*x = GetAllHostServersRequest{}
	mi := &file_internal_proto_host_metadata_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllHostServersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllHostServersRequest) ProtoMessage() {}

func (x *GetAllHostServersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_host_metadata_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllHostServersRequest.ProtoReflect.Descriptor instead.
func (*GetAllHostServersRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_host_metadata_service_proto_rawDescGZIP(), []int{4}
}

type HostServer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Servers       []string               `protobuf:"bytes,2,rep,name=servers,proto3" json:"servers,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostServer) Reset() {
	*x = HostServer{}
	mi := &file_internal_proto_host_metadata_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostServer) ProtoMessage() {}

func (x *HostServer) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_host_metadata_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostServer.ProtoReflect.Descriptor instead.
func (*HostServer) Descriptor() ([]byte, []int) {
	return file_internal_proto_host_metadata_service_proto_rawDescGZIP(), []int{5}
}

func (x *HostServer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HostServer) GetServers() []string {
	if x != nil {
		return x.Servers
	}
	return nil
}

func (x *HostServer) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetAllHostServersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hosts         []*HostServer          `protobuf:"bytes,1,rep,name=hosts,proto3" json:"hosts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllHostServersResponse) Reset() {
	*x = GetAllHostServersResponse{}
	mi := &file_internal_proto_host_metadata_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllHostServersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllHostServersResponse) ProtoMessage() {}

func (x *GetAllHostServersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_host_metadata_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllHostServersResponse.ProtoReflect.Descriptor instead.
func (*GetAllHostServersResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_host_metadata_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetAllHostServersResponse) GetHosts() []*HostServer {
	if x != nil {
		return x.Hosts
	}
	return nil
}

type AddServerToHostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostServerId  string                 `protobuf:"bytes,1,opt,name=host_server_id,json=hostServerId,proto3" json:"host_server_id,omitempty"`
	ServerId      string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddServerToHostRequest) Reset() {
	*x = AddServerToHostRequest{}
	mi := &file_internal_proto_host_metadata_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddServerToHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddServerToHostRequest) ProtoMessage() {}

func (x *AddServerToHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_host_metadata_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddServerToHostRequest.ProtoReflect.Descriptor instead.
func (*AddServerToHostRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_host_metadata_service_proto_rawDescGZIP(), []int{7}
}

func (x *AddServerToHostRequest) GetHostServerId() string {
	if x != nil {
		return x.HostServerId
	}
	return ""
}

func (x *AddServerToHostRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

type AddServerToHostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddServerToHostResponse) Reset() {
	*x = AddServerToHostResponse{}
	mi := &file_internal_proto_host_metadata_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddServerToHostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddServerToHostResponse) ProtoMessage() {}

func (x *AddServerToHostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_host_metadata_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddServerToHostResponse.ProtoReflect.Descriptor instead.
func (*AddServerToHostResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_host_metadata_service_proto_rawDescGZIP(), []int{8}
}

var File_internal_proto_host_metadata_service_proto protoreflect.FileDescriptor

const file_internal_proto_host_metadata_service_proto_rawDesc = "" +
	"\n" +
	"*internal/proto/host-metadata-service.proto\x12\x15host_metadata_service\"\x19\n" +
	"\x17CreateHostServerRequest\"@\n" +
	"\x18CreateHostServerResponse\x12$\n" +
	"\x0ehost_server_id\x18\x01 \x01(\tR\fhostServerId\"?\n" +
	"\x17DeleteHostServerRequest\x12$\n" +
	"\x0ehost_server_id\x18\x01 \x01(\tR\fhostServerId\"\x1a\n" +
	"\x18DeleteHostServerResponse\"\x1a\n" +
	"\x18GetAllHostServersRequest\"U\n" +
	"\n" +
	"HostServer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aservers\x18\x02 \x03(\tR\aservers\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\"T\n" +
	"\x19GetAllHostServersResponse\x127\n" +
	"\x05hosts\x18\x01 \x03(\v2!.host_metadata_service.HostServerR\x05hosts\"[\n" +
	"\x16AddServerToHostRequest\x12$\n" +
	"\x0ehost_server_id\x18\x01 \x01(\tR\fhostServerId\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\"\x19\n" +
	"\x17AddServerToHostResponse2\xe9\x03\n" +
	"\x13HostMetadataService\x12s\n" +
	"\x10CreateHostServer\x12..host_metadata_service.CreateHostServerRequest\x1a/.host_metadata_service.CreateHostServerResponse\x12s\n" +
	"\x10DeleteHostServer\x12..host_metadata_service.DeleteHostServerRequest\x1a/.host_metadata_service.DeleteHostServerResponse\x12v\n" +
	"\x11GetAllHostServers\x12/.host_metadata_service.GetAllHostServersRequest\x1a0.host_metadata_service.GetAllHostServersResponse\x12p\n" +
	"\x0fAddServerToHost\x12-.host_metadata_service.AddServerToHostRequest\x1a..host_metadata_service.AddServerToHostResponseB\x17Z\x15/internal/proto;protob\x06proto3"

var (
	file_internal_proto_host_metadata_service_proto_rawDescOnce sync.Once
	file_internal_proto_host_metadata_service_proto_rawDescData []byte
)

func file_internal_proto_host_metadata_service_proto_rawDescGZIP() []byte {
	file_internal_proto_host_metadata_service_proto_rawDescOnce.Do(func() {
		file_internal_proto_host_metadata_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_host_metadata_service_proto_rawDesc), len(file_internal_proto_host_metadata_service_proto_rawDesc)))
	})
	return file_internal_proto_host_metadata_service_proto_rawDescData
}

var file_internal_proto_host_metadata_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_internal_proto_host_metadata_service_proto_goTypes = []any{
	(*CreateHostServerRequest)(nil),   // 0: host_metadata_service.CreateHostServerRequest
	(*CreateHostServerResponse)(nil),  // 1: host_metadata_service.CreateHostServerResponse
	(*DeleteHostServerRequest)(nil),   // 2: host_metadata_service.DeleteHostServerRequest
	(*DeleteHostServerResponse)(nil),  // 3: host_metadata_service.DeleteHostServerResponse
	(*GetAllHostServersRequest)(nil),  // 4: host_metadata_service.GetAllHostServersRequest
	(*HostServer)(nil),                // 5: host_metadata_service.HostServer
	(*GetAllHostServersResponse)(nil), // 6: host_metadata_service.GetAllHostServersResponse
	(*AddServerToHostRequest)(nil),    // 7: host_metadata_service.AddServerToHostRequest
	(*AddServerToHostResponse)(nil),   // 8: host_metadata_service.AddServerToHostResponse
}
var file_internal_proto_host_metadata_service_proto_depIdxs = []int32{
	5, // 0: host_metadata_service.GetAllHostServersResponse.hosts:type_name -> host_metadata_service.HostServer
	0, // 1: host_metadata_service.HostMetadataService.CreateHostServer:input_type -> host_metadata_service.CreateHostServerRequest
	2, // 2: host_metadata_service.HostMetadataService.DeleteHostServer:input_type -> host_metadata_service.DeleteHostServerRequest
	4, // 3: host_metadata_service.HostMetadataService.GetAllHostServers:input_type -> host_metadata_service.GetAllHostServersRequest
	7, // 4: host_metadata_service.HostMetadataService.AddServerToHost:input_type -> host_metadata_service.AddServerToHostRequest
	1, // 5: host_metadata_service.HostMetadataService.CreateHostServer:output_type -> host_metadata_service.CreateHostServerResponse
	3, // 6: host_metadata_service.HostMetadataService.DeleteHostServer:output_type -> host_metadata_service.DeleteHostServerResponse
	6, // 7: host_metadata_service.HostMetadataService.GetAllHostServers:output_type -> host_metadata_service.GetAllHostServersResponse
	8, // 8: host_metadata_service.HostMetadataService.AddServerToHost:output_type -> host_metadata_service.AddServerToHostResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_proto_host_metadata_service_proto_init() }
func file_internal_proto_host_metadata_service_proto_init() {
	if File_internal_proto_host_metadata_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_host_metadata_service_proto_rawDesc), len(file_internal_proto_host_metadata_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_host_metadata_service_proto_goTypes,
		DependencyIndexes: file_internal_proto_host_metadata_service_proto_depIdxs,
		MessageInfos:      file_internal_proto_host_metadata_service_proto_msgTypes,
	}.Build()
	File_internal_proto_host_metadata_service_proto = out.File
	file_internal_proto_host_metadata_service_proto_goTypes = nil
	file_internal_proto_host_metadata_service_proto_depIdxs = nil
}
