// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.30.2
// source: internal/proto/user-service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SaveUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveUserRequest) Reset() {
	*x = SaveUserRequest{}
	mi := &file_internal_proto_user_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveUserRequest) ProtoMessage() {}

func (x *SaveUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_user_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveUserRequest.ProtoReflect.Descriptor instead.
func (*SaveUserRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_user_service_proto_rawDescGZIP(), []int{0}
}

func (x *SaveUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SaveUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *SaveUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type SaveUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveUserResponse) Reset() {
	*x = SaveUserResponse{}
	mi := &file_internal_proto_user_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveUserResponse) ProtoMessage() {}

func (x *SaveUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_user_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveUserResponse.ProtoReflect.Descriptor instead.
func (*SaveUserResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_user_service_proto_rawDescGZIP(), []int{1}
}

func (x *SaveUserResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SaveUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetUserPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPasswordRequest) Reset() {
	*x = GetUserPasswordRequest{}
	mi := &file_internal_proto_user_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPasswordRequest) ProtoMessage() {}

func (x *GetUserPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_user_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPasswordRequest.ProtoReflect.Descriptor instead.
func (*GetUserPasswordRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_user_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserPasswordRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetUserPasswordRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type GetUserPasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Password      string                 `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPasswordResponse) Reset() {
	*x = GetUserPasswordResponse{}
	mi := &file_internal_proto_user_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPasswordResponse) ProtoMessage() {}

func (x *GetUserPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_user_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPasswordResponse.ProtoReflect.Descriptor instead.
func (*GetUserPasswordResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_user_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserPasswordResponse) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

var File_internal_proto_user_service_proto protoreflect.FileDescriptor

const file_internal_proto_user_service_proto_rawDesc = "" +
	"\n" +
	"!internal/proto/user-service.proto\x12\fuser_service\"_\n" +
	"\x0fSaveUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"<\n" +
	"\x10SaveUserResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"D\n" +
	"\x16GetUserPasswordRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"5\n" +
	"\x17GetUserPasswordResponse\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword2\xb8\x01\n" +
	"\vUserService\x12I\n" +
	"\bSaveUser\x12\x1d.user_service.SaveUserRequest\x1a\x1e.user_service.SaveUserResponse\x12^\n" +
	"\x0fGetUserPassword\x12$.user_service.GetUserPasswordRequest\x1a%.user_service.GetUserPasswordResponseB\x17Z\x15/internal/proto;protob\x06proto3"

var (
	file_internal_proto_user_service_proto_rawDescOnce sync.Once
	file_internal_proto_user_service_proto_rawDescData []byte
)

func file_internal_proto_user_service_proto_rawDescGZIP() []byte {
	file_internal_proto_user_service_proto_rawDescOnce.Do(func() {
		file_internal_proto_user_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_user_service_proto_rawDesc), len(file_internal_proto_user_service_proto_rawDesc)))
	})
	return file_internal_proto_user_service_proto_rawDescData
}

var file_internal_proto_user_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_proto_user_service_proto_goTypes = []any{
	(*SaveUserRequest)(nil),         // 0: user_service.SaveUserRequest
	(*SaveUserResponse)(nil),        // 1: user_service.SaveUserResponse
	(*GetUserPasswordRequest)(nil),  // 2: user_service.GetUserPasswordRequest
	(*GetUserPasswordResponse)(nil), // 3: user_service.GetUserPasswordResponse
}
var file_internal_proto_user_service_proto_depIdxs = []int32{
	0, // 0: user_service.UserService.SaveUser:input_type -> user_service.SaveUserRequest
	2, // 1: user_service.UserService.GetUserPassword:input_type -> user_service.GetUserPasswordRequest
	1, // 2: user_service.UserService.SaveUser:output_type -> user_service.SaveUserResponse
	3, // 3: user_service.UserService.GetUserPassword:output_type -> user_service.GetUserPasswordResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_user_service_proto_init() }
func file_internal_proto_user_service_proto_init() {
	if File_internal_proto_user_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_user_service_proto_rawDesc), len(file_internal_proto_user_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_user_service_proto_goTypes,
		DependencyIndexes: file_internal_proto_user_service_proto_depIdxs,
		MessageInfos:      file_internal_proto_user_service_proto_msgTypes,
	}.Build()
	File_internal_proto_user_service_proto = out.File
	file_internal_proto_user_service_proto_goTypes = nil
	file_internal_proto_user_service_proto_depIdxs = nil
}
