// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v6.30.2
// source: internal/proto/host-metadata-service/host-metadata-service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateHostServerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ram   string `protobuf:"bytes,1,opt,name=ram,proto3" json:"ram,omitempty"`
	Cores string `protobuf:"bytes,2,opt,name=cores,proto3" json:"cores,omitempty"`
}

func (x *CreateHostServerRequest) Reset() {
	*x = CreateHostServerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_host_metadata_service_host_metadata_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateHostServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHostServerRequest) ProtoMessage() {}

func (x *CreateHostServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_host_metadata_service_host_metadata_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHostServerRequest.ProtoReflect.Descriptor instead.
func (*CreateHostServerRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_host_metadata_service_host_metadata_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateHostServerRequest) GetRam() string {
	if x != nil {
		return x.Ram
	}
	return ""
}

func (x *CreateHostServerRequest) GetCores() string {
	if x != nil {
		return x.Cores
	}
	return ""
}

type CreateHostServerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HostServerId string `protobuf:"bytes,1,opt,name=host_server_id,json=hostServerId,proto3" json:"host_server_id,omitempty"`
}

func (x *CreateHostServerResponse) Reset() {
	*x = CreateHostServerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_host_metadata_service_host_metadata_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateHostServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHostServerResponse) ProtoMessage() {}

func (x *CreateHostServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_host_metadata_service_host_metadata_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHostServerResponse.ProtoReflect.Descriptor instead.
func (*CreateHostServerResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_host_metadata_service_host_metadata_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateHostServerResponse) GetHostServerId() string {
	if x != nil {
		return x.HostServerId
	}
	return ""
}

type DeleteHostServerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HostServerId string `protobuf:"bytes,1,opt,name=host_server_id,json=hostServerId,proto3" json:"host_server_id,omitempty"`
}

func (x *DeleteHostServerRequest) Reset() {
	*x = DeleteHostServerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_host_metadata_service_host_metadata_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteHostServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHostServerRequest) ProtoMessage() {}

func (x *DeleteHostServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_host_metadata_service_host_metadata_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHostServerRequest.ProtoReflect.Descriptor instead.
func (*DeleteHostServerRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_host_metadata_service_host_metadata_service_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteHostServerRequest) GetHostServerId() string {
	if x != nil {
		return x.HostServerId
	}
	return ""
}

type DeleteHostServerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteHostServerResponse) Reset() {
	*x = DeleteHostServerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_host_metadata_service_host_metadata_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteHostServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHostServerResponse) ProtoMessage() {}

func (x *DeleteHostServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_host_metadata_service_host_metadata_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHostServerResponse.ProtoReflect.Descriptor instead.
func (*DeleteHostServerResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_host_metadata_service_host_metadata_service_proto_rawDescGZIP(), []int{3}
}

type GetAllHostServersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAllHostServersRequest) Reset() {
	*x = GetAllHostServersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_host_metadata_service_host_metadata_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllHostServersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllHostServersRequest) ProtoMessage() {}

func (x *GetAllHostServersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_host_metadata_service_host_metadata_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllHostServersRequest.ProtoReflect.Descriptor instead.
func (*GetAllHostServersRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_host_metadata_service_host_metadata_service_proto_rawDescGZIP(), []int{4}
}

type HostServer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Servers   []string `protobuf:"bytes,2,rep,name=servers,proto3" json:"servers,omitempty"`
	CreatedAt string   `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *HostServer) Reset() {
	*x = HostServer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_host_metadata_service_host_metadata_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostServer) ProtoMessage() {}

func (x *HostServer) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_host_metadata_service_host_metadata_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostServer.ProtoReflect.Descriptor instead.
func (*HostServer) Descriptor() ([]byte, []int) {
	return file_internal_proto_host_metadata_service_host_metadata_service_proto_rawDescGZIP(), []int{5}
}

func (x *HostServer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HostServer) GetServers() []string {
	if x != nil {
		return x.Servers
	}
	return nil
}

func (x *HostServer) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetAllHostServersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hosts []*HostServer `protobuf:"bytes,1,rep,name=hosts,proto3" json:"hosts,omitempty"`
}

func (x *GetAllHostServersResponse) Reset() {
	*x = GetAllHostServersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_host_metadata_service_host_metadata_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllHostServersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllHostServersResponse) ProtoMessage() {}

func (x *GetAllHostServersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_host_metadata_service_host_metadata_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllHostServersResponse.ProtoReflect.Descriptor instead.
func (*GetAllHostServersResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_host_metadata_service_host_metadata_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetAllHostServersResponse) GetHosts() []*HostServer {
	if x != nil {
		return x.Hosts
	}
	return nil
}

type AddServerToHostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HostServerId string `protobuf:"bytes,1,opt,name=host_server_id,json=hostServerId,proto3" json:"host_server_id,omitempty"`
	ServerId     string `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
}

func (x *AddServerToHostRequest) Reset() {
	*x = AddServerToHostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_host_metadata_service_host_metadata_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddServerToHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddServerToHostRequest) ProtoMessage() {}

func (x *AddServerToHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_host_metadata_service_host_metadata_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddServerToHostRequest.ProtoReflect.Descriptor instead.
func (*AddServerToHostRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_host_metadata_service_host_metadata_service_proto_rawDescGZIP(), []int{7}
}

func (x *AddServerToHostRequest) GetHostServerId() string {
	if x != nil {
		return x.HostServerId
	}
	return ""
}

func (x *AddServerToHostRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

type AddServerToHostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddServerToHostResponse) Reset() {
	*x = AddServerToHostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_host_metadata_service_host_metadata_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddServerToHostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddServerToHostResponse) ProtoMessage() {}

func (x *AddServerToHostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_host_metadata_service_host_metadata_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddServerToHostResponse.ProtoReflect.Descriptor instead.
func (*AddServerToHostResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_host_metadata_service_host_metadata_service_proto_rawDescGZIP(), []int{8}
}

type RemoveServerFromHostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HostServerId string `protobuf:"bytes,1,opt,name=host_server_id,json=hostServerId,proto3" json:"host_server_id,omitempty"`
	ServerId     string `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
}

func (x *RemoveServerFromHostRequest) Reset() {
	*x = RemoveServerFromHostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_host_metadata_service_host_metadata_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveServerFromHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveServerFromHostRequest) ProtoMessage() {}

func (x *RemoveServerFromHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_host_metadata_service_host_metadata_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveServerFromHostRequest.ProtoReflect.Descriptor instead.
func (*RemoveServerFromHostRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_host_metadata_service_host_metadata_service_proto_rawDescGZIP(), []int{9}
}

func (x *RemoveServerFromHostRequest) GetHostServerId() string {
	if x != nil {
		return x.HostServerId
	}
	return ""
}

func (x *RemoveServerFromHostRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

type RemoveServerFromHostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RemoveServerFromHostResponse) Reset() {
	*x = RemoveServerFromHostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_host_metadata_service_host_metadata_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveServerFromHostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveServerFromHostResponse) ProtoMessage() {}

func (x *RemoveServerFromHostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_host_metadata_service_host_metadata_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveServerFromHostResponse.ProtoReflect.Descriptor instead.
func (*RemoveServerFromHostResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_host_metadata_service_host_metadata_service_proto_rawDescGZIP(), []int{10}
}

type GetRAMRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HostServerId string `protobuf:"bytes,1,opt,name=host_server_id,json=hostServerId,proto3" json:"host_server_id,omitempty"`
}

func (x *GetRAMRequest) Reset() {
	*x = GetRAMRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_host_metadata_service_host_metadata_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRAMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRAMRequest) ProtoMessage() {}

func (x *GetRAMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_host_metadata_service_host_metadata_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRAMRequest.ProtoReflect.Descriptor instead.
func (*GetRAMRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_host_metadata_service_host_metadata_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetRAMRequest) GetHostServerId() string {
	if x != nil {
		return x.HostServerId
	}
	return ""
}

type GetRAMResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ram string `protobuf:"bytes,1,opt,name=ram,proto3" json:"ram,omitempty"`
}

func (x *GetRAMResponse) Reset() {
	*x = GetRAMResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_host_metadata_service_host_metadata_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRAMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRAMResponse) ProtoMessage() {}

func (x *GetRAMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_host_metadata_service_host_metadata_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRAMResponse.ProtoReflect.Descriptor instead.
func (*GetRAMResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_host_metadata_service_host_metadata_service_proto_rawDescGZIP(), []int{12}
}

func (x *GetRAMResponse) GetRam() string {
	if x != nil {
		return x.Ram
	}
	return ""
}

type GetCoresRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HostServerId string `protobuf:"bytes,1,opt,name=host_server_id,json=hostServerId,proto3" json:"host_server_id,omitempty"`
}

func (x *GetCoresRequest) Reset() {
	*x = GetCoresRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_host_metadata_service_host_metadata_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCoresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoresRequest) ProtoMessage() {}

func (x *GetCoresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_host_metadata_service_host_metadata_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoresRequest.ProtoReflect.Descriptor instead.
func (*GetCoresRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_host_metadata_service_host_metadata_service_proto_rawDescGZIP(), []int{13}
}

func (x *GetCoresRequest) GetHostServerId() string {
	if x != nil {
		return x.HostServerId
	}
	return ""
}

type GetCoresResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cores string `protobuf:"bytes,1,opt,name=cores,proto3" json:"cores,omitempty"`
}

func (x *GetCoresResponse) Reset() {
	*x = GetCoresResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_host_metadata_service_host_metadata_service_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCoresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoresResponse) ProtoMessage() {}

func (x *GetCoresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_host_metadata_service_host_metadata_service_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoresResponse.ProtoReflect.Descriptor instead.
func (*GetCoresResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_host_metadata_service_host_metadata_service_proto_rawDescGZIP(), []int{14}
}

func (x *GetCoresResponse) GetCores() string {
	if x != nil {
		return x.Cores
	}
	return ""
}

type SubtractRAMRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HostServerId string `protobuf:"bytes,1,opt,name=host_server_id,json=hostServerId,proto3" json:"host_server_id,omitempty"`
	Ram          string `protobuf:"bytes,2,opt,name=ram,proto3" json:"ram,omitempty"`
}

func (x *SubtractRAMRequest) Reset() {
	*x = SubtractRAMRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_host_metadata_service_host_metadata_service_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubtractRAMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubtractRAMRequest) ProtoMessage() {}

func (x *SubtractRAMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_host_metadata_service_host_metadata_service_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubtractRAMRequest.ProtoReflect.Descriptor instead.
func (*SubtractRAMRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_host_metadata_service_host_metadata_service_proto_rawDescGZIP(), []int{15}
}

func (x *SubtractRAMRequest) GetHostServerId() string {
	if x != nil {
		return x.HostServerId
	}
	return ""
}

func (x *SubtractRAMRequest) GetRam() string {
	if x != nil {
		return x.Ram
	}
	return ""
}

type SubtractRAMResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SubtractRAMResponse) Reset() {
	*x = SubtractRAMResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_host_metadata_service_host_metadata_service_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubtractRAMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubtractRAMResponse) ProtoMessage() {}

func (x *SubtractRAMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_host_metadata_service_host_metadata_service_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubtractRAMResponse.ProtoReflect.Descriptor instead.
func (*SubtractRAMResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_host_metadata_service_host_metadata_service_proto_rawDescGZIP(), []int{16}
}

type SubtractCoresRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HostServerId string `protobuf:"bytes,1,opt,name=host_server_id,json=hostServerId,proto3" json:"host_server_id,omitempty"`
	Cores        string `protobuf:"bytes,2,opt,name=cores,proto3" json:"cores,omitempty"`
}

func (x *SubtractCoresRequest) Reset() {
	*x = SubtractCoresRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_host_metadata_service_host_metadata_service_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubtractCoresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubtractCoresRequest) ProtoMessage() {}

func (x *SubtractCoresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_host_metadata_service_host_metadata_service_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubtractCoresRequest.ProtoReflect.Descriptor instead.
func (*SubtractCoresRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_host_metadata_service_host_metadata_service_proto_rawDescGZIP(), []int{17}
}

func (x *SubtractCoresRequest) GetHostServerId() string {
	if x != nil {
		return x.HostServerId
	}
	return ""
}

func (x *SubtractCoresRequest) GetCores() string {
	if x != nil {
		return x.Cores
	}
	return ""
}

type SubtractCoresResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SubtractCoresResponse) Reset() {
	*x = SubtractCoresResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_host_metadata_service_host_metadata_service_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubtractCoresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubtractCoresResponse) ProtoMessage() {}

func (x *SubtractCoresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_host_metadata_service_host_metadata_service_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubtractCoresResponse.ProtoReflect.Descriptor instead.
func (*SubtractCoresResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_host_metadata_service_host_metadata_service_proto_rawDescGZIP(), []int{18}
}

var File_internal_proto_host_metadata_service_host_metadata_service_proto protoreflect.FileDescriptor

var file_internal_proto_host_metadata_service_host_metadata_service_proto_rawDesc = []byte{
	0x0a, 0x40, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x68, 0x6f, 0x73, 0x74, 0x2d, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2d, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x68, 0x6f, 0x73, 0x74, 0x2d, 0x6d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x15, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x41, 0x0a, 0x17, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x61, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x72, 0x61, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x22, 0x40, 0x0a, 0x18,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x0e, 0x68, 0x6f, 0x73, 0x74,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x68, 0x6f, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x22, 0x3f,
	0x0a, 0x17, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x0e, 0x68, 0x6f, 0x73,
	0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x68, 0x6f, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x22,
	0x1a, 0x0a, 0x18, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1a, 0x0a, 0x18, 0x47,
	0x65, 0x74, 0x41, 0x6c, 0x6c, 0x48, 0x6f, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x55, 0x0a, 0x0a, 0x48, 0x6f, 0x73, 0x74, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x12,
	0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x54,
	0x0a, 0x19, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x48, 0x6f, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x05, 0x68,
	0x6f, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x68, 0x6f, 0x73,
	0x74, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x05, 0x68,
	0x6f, 0x73, 0x74, 0x73, 0x22, 0x5b, 0x0a, 0x16, 0x41, 0x64, 0x64, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x54, 0x6f, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24,
	0x0a, 0x0e, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x68, 0x6f, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49,
	0x64, 0x22, 0x19, 0x0a, 0x17, 0x41, 0x64, 0x64, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x6f,
	0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x60, 0x0a, 0x1b,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x46, 0x72, 0x6f, 0x6d,
	0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x0e, 0x68,
	0x6f, 0x73, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x68, 0x6f, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x22, 0x1e,
	0x0a, 0x1c, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x46, 0x72,
	0x6f, 0x6d, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x35,
	0x0a, 0x0d, 0x47, 0x65, 0x74, 0x52, 0x41, 0x4d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x24, 0x0a, 0x0e, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x68, 0x6f, 0x73, 0x74, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x49, 0x64, 0x22, 0x22, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x52, 0x41, 0x4d, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x61, 0x6d, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x61, 0x6d, 0x22, 0x37, 0x0a, 0x0f, 0x47, 0x65, 0x74,
	0x43, 0x6f, 0x72, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x0e,
	0x68, 0x6f, 0x73, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x68, 0x6f, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x49, 0x64, 0x22, 0x28, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x72, 0x65, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x22, 0x4c, 0x0a, 0x12,
	0x53, 0x75, 0x62, 0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x41, 0x4d, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x24, 0x0a, 0x0e, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x68, 0x6f, 0x73, 0x74,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x61, 0x6d, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x61, 0x6d, 0x22, 0x15, 0x0a, 0x13, 0x53, 0x75,
	0x62, 0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x41, 0x4d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x52, 0x0a, 0x14, 0x53, 0x75, 0x62, 0x74, 0x72, 0x61, 0x63, 0x74, 0x43, 0x6f, 0x72,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x0e, 0x68, 0x6f, 0x73,
	0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x68, 0x6f, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x63, 0x6f, 0x72, 0x65, 0x73, 0x22, 0x17, 0x0a, 0x15, 0x53, 0x75, 0x62, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x43, 0x6f, 0x72, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xf0,
	0x07, 0x0a, 0x13, 0x48, 0x6f, 0x73, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x73, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x48, 0x6f, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x2e, 0x2e, 0x68, 0x6f, 0x73,
	0x74, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2f, 0x2e, 0x68, 0x6f, 0x73,
	0x74, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x73, 0x0a, 0x10, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12,
	0x2e, 0x2e, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x48, 0x6f,
	0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x2f, 0x2e, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x48, 0x6f,
	0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x76, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x48, 0x6f, 0x73, 0x74, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x73, 0x12, 0x2f, 0x2e, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x6d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65,
	0x74, 0x41, 0x6c, 0x6c, 0x48, 0x6f, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x30, 0x2e, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x6d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47,
	0x65, 0x74, 0x41, 0x6c, 0x6c, 0x48, 0x6f, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x70, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x6f, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x2d, 0x2e, 0x68, 0x6f,
	0x73, 0x74, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x6f, 0x48,
	0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e, 0x2e, 0x68, 0x6f, 0x73,
	0x74, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x6f, 0x48, 0x6f,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x7f, 0x0a, 0x14, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x46, 0x72, 0x6f, 0x6d, 0x48, 0x6f,
	0x73, 0x74, 0x12, 0x32, 0x2e, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x46, 0x72, 0x6f, 0x6d, 0x48, 0x6f, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x33, 0x2e, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x6d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x46, 0x72, 0x6f, 0x6d, 0x48,
	0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x55, 0x0a, 0x06, 0x47,
	0x65, 0x74, 0x52, 0x41, 0x4d, 0x12, 0x24, 0x2e, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x6d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65,
	0x74, 0x52, 0x41, 0x4d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x68, 0x6f,
	0x73, 0x74, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x41, 0x4d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x5b, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x72, 0x65, 0x73, 0x12, 0x26,
	0x2e, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x72, 0x65, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x6d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47,
	0x65, 0x74, 0x43, 0x6f, 0x72, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x64, 0x0a, 0x0b, 0x53, 0x75, 0x62, 0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x41, 0x4d, 0x12, 0x29,
	0x2e, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x75, 0x62, 0x74, 0x72, 0x61, 0x63, 0x74, 0x52,
	0x41, 0x4d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x68, 0x6f, 0x73, 0x74,
	0x5f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x53, 0x75, 0x62, 0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x41, 0x4d, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6a, 0x0a, 0x0d, 0x53, 0x75, 0x62, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x43, 0x6f, 0x72, 0x65, 0x73, 0x12, 0x2b, 0x2e, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x6d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53,
	0x75, 0x62, 0x74, 0x72, 0x61, 0x63, 0x74, 0x43, 0x6f, 0x72, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x75, 0x62, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x43, 0x6f, 0x72, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x2d, 0x5a, 0x2b, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x68,
	0x6f, 0x73, 0x74, 0x2d, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2d, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_proto_host_metadata_service_host_metadata_service_proto_rawDescOnce sync.Once
	file_internal_proto_host_metadata_service_host_metadata_service_proto_rawDescData = file_internal_proto_host_metadata_service_host_metadata_service_proto_rawDesc
)

func file_internal_proto_host_metadata_service_host_metadata_service_proto_rawDescGZIP() []byte {
	file_internal_proto_host_metadata_service_host_metadata_service_proto_rawDescOnce.Do(func() {
		file_internal_proto_host_metadata_service_host_metadata_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_proto_host_metadata_service_host_metadata_service_proto_rawDescData)
	})
	return file_internal_proto_host_metadata_service_host_metadata_service_proto_rawDescData
}

var file_internal_proto_host_metadata_service_host_metadata_service_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_internal_proto_host_metadata_service_host_metadata_service_proto_goTypes = []interface{}{
	(*CreateHostServerRequest)(nil),      // 0: host_metadata_service.CreateHostServerRequest
	(*CreateHostServerResponse)(nil),     // 1: host_metadata_service.CreateHostServerResponse
	(*DeleteHostServerRequest)(nil),      // 2: host_metadata_service.DeleteHostServerRequest
	(*DeleteHostServerResponse)(nil),     // 3: host_metadata_service.DeleteHostServerResponse
	(*GetAllHostServersRequest)(nil),     // 4: host_metadata_service.GetAllHostServersRequest
	(*HostServer)(nil),                   // 5: host_metadata_service.HostServer
	(*GetAllHostServersResponse)(nil),    // 6: host_metadata_service.GetAllHostServersResponse
	(*AddServerToHostRequest)(nil),       // 7: host_metadata_service.AddServerToHostRequest
	(*AddServerToHostResponse)(nil),      // 8: host_metadata_service.AddServerToHostResponse
	(*RemoveServerFromHostRequest)(nil),  // 9: host_metadata_service.RemoveServerFromHostRequest
	(*RemoveServerFromHostResponse)(nil), // 10: host_metadata_service.RemoveServerFromHostResponse
	(*GetRAMRequest)(nil),                // 11: host_metadata_service.GetRAMRequest
	(*GetRAMResponse)(nil),               // 12: host_metadata_service.GetRAMResponse
	(*GetCoresRequest)(nil),              // 13: host_metadata_service.GetCoresRequest
	(*GetCoresResponse)(nil),             // 14: host_metadata_service.GetCoresResponse
	(*SubtractRAMRequest)(nil),           // 15: host_metadata_service.SubtractRAMRequest
	(*SubtractRAMResponse)(nil),          // 16: host_metadata_service.SubtractRAMResponse
	(*SubtractCoresRequest)(nil),         // 17: host_metadata_service.SubtractCoresRequest
	(*SubtractCoresResponse)(nil),        // 18: host_metadata_service.SubtractCoresResponse
}
var file_internal_proto_host_metadata_service_host_metadata_service_proto_depIdxs = []int32{
	5,  // 0: host_metadata_service.GetAllHostServersResponse.hosts:type_name -> host_metadata_service.HostServer
	0,  // 1: host_metadata_service.HostMetadataService.CreateHostServer:input_type -> host_metadata_service.CreateHostServerRequest
	2,  // 2: host_metadata_service.HostMetadataService.DeleteHostServer:input_type -> host_metadata_service.DeleteHostServerRequest
	4,  // 3: host_metadata_service.HostMetadataService.GetAllHostServers:input_type -> host_metadata_service.GetAllHostServersRequest
	7,  // 4: host_metadata_service.HostMetadataService.AddServerToHost:input_type -> host_metadata_service.AddServerToHostRequest
	9,  // 5: host_metadata_service.HostMetadataService.RemoveServerFromHost:input_type -> host_metadata_service.RemoveServerFromHostRequest
	11, // 6: host_metadata_service.HostMetadataService.GetRAM:input_type -> host_metadata_service.GetRAMRequest
	13, // 7: host_metadata_service.HostMetadataService.GetCores:input_type -> host_metadata_service.GetCoresRequest
	15, // 8: host_metadata_service.HostMetadataService.SubtractRAM:input_type -> host_metadata_service.SubtractRAMRequest
	17, // 9: host_metadata_service.HostMetadataService.SubtractCores:input_type -> host_metadata_service.SubtractCoresRequest
	1,  // 10: host_metadata_service.HostMetadataService.CreateHostServer:output_type -> host_metadata_service.CreateHostServerResponse
	3,  // 11: host_metadata_service.HostMetadataService.DeleteHostServer:output_type -> host_metadata_service.DeleteHostServerResponse
	6,  // 12: host_metadata_service.HostMetadataService.GetAllHostServers:output_type -> host_metadata_service.GetAllHostServersResponse
	8,  // 13: host_metadata_service.HostMetadataService.AddServerToHost:output_type -> host_metadata_service.AddServerToHostResponse
	10, // 14: host_metadata_service.HostMetadataService.RemoveServerFromHost:output_type -> host_metadata_service.RemoveServerFromHostResponse
	12, // 15: host_metadata_service.HostMetadataService.GetRAM:output_type -> host_metadata_service.GetRAMResponse
	14, // 16: host_metadata_service.HostMetadataService.GetCores:output_type -> host_metadata_service.GetCoresResponse
	16, // 17: host_metadata_service.HostMetadataService.SubtractRAM:output_type -> host_metadata_service.SubtractRAMResponse
	18, // 18: host_metadata_service.HostMetadataService.SubtractCores:output_type -> host_metadata_service.SubtractCoresResponse
	10, // [10:19] is the sub-list for method output_type
	1,  // [1:10] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_internal_proto_host_metadata_service_host_metadata_service_proto_init() }
func file_internal_proto_host_metadata_service_host_metadata_service_proto_init() {
	if File_internal_proto_host_metadata_service_host_metadata_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_proto_host_metadata_service_host_metadata_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateHostServerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_host_metadata_service_host_metadata_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateHostServerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_host_metadata_service_host_metadata_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteHostServerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_host_metadata_service_host_metadata_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteHostServerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_host_metadata_service_host_metadata_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllHostServersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_host_metadata_service_host_metadata_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostServer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_host_metadata_service_host_metadata_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllHostServersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_host_metadata_service_host_metadata_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddServerToHostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_host_metadata_service_host_metadata_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddServerToHostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_host_metadata_service_host_metadata_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveServerFromHostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_host_metadata_service_host_metadata_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveServerFromHostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_host_metadata_service_host_metadata_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRAMRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_host_metadata_service_host_metadata_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRAMResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_host_metadata_service_host_metadata_service_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCoresRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_host_metadata_service_host_metadata_service_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCoresResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_host_metadata_service_host_metadata_service_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubtractRAMRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_host_metadata_service_host_metadata_service_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubtractRAMResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_host_metadata_service_host_metadata_service_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubtractCoresRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_host_metadata_service_host_metadata_service_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubtractCoresResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_proto_host_metadata_service_host_metadata_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_host_metadata_service_host_metadata_service_proto_goTypes,
		DependencyIndexes: file_internal_proto_host_metadata_service_host_metadata_service_proto_depIdxs,
		MessageInfos:      file_internal_proto_host_metadata_service_host_metadata_service_proto_msgTypes,
	}.Build()
	File_internal_proto_host_metadata_service_host_metadata_service_proto = out.File
	file_internal_proto_host_metadata_service_host_metadata_service_proto_rawDesc = nil
	file_internal_proto_host_metadata_service_host_metadata_service_proto_goTypes = nil
	file_internal_proto_host_metadata_service_host_metadata_service_proto_depIdxs = nil
}
