// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: internal/proto/host-metadata-service/host-metadata-service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HostMetadataService_CreateHostServer_FullMethodName     = "/host_metadata_service.HostMetadataService/CreateHostServer"
	HostMetadataService_DeleteHostServer_FullMethodName     = "/host_metadata_service.HostMetadataService/DeleteHostServer"
	HostMetadataService_GetAllHostServers_FullMethodName    = "/host_metadata_service.HostMetadataService/GetAllHostServers"
	HostMetadataService_AddServerToHost_FullMethodName      = "/host_metadata_service.HostMetadataService/AddServerToHost"
	HostMetadataService_RemoveServerFromHost_FullMethodName = "/host_metadata_service.HostMetadataService/RemoveServerFromHost"
)

// HostMetadataServiceClient is the client API for HostMetadataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HostMetadataServiceClient interface {
	CreateHostServer(ctx context.Context, in *CreateHostServerRequest, opts ...grpc.CallOption) (*CreateHostServerResponse, error)
	DeleteHostServer(ctx context.Context, in *DeleteHostServerRequest, opts ...grpc.CallOption) (*DeleteHostServerResponse, error)
	GetAllHostServers(ctx context.Context, in *GetAllHostServersRequest, opts ...grpc.CallOption) (*GetAllHostServersResponse, error)
	AddServerToHost(ctx context.Context, in *AddServerToHostRequest, opts ...grpc.CallOption) (*AddServerToHostResponse, error)
	RemoveServerFromHost(ctx context.Context, in *RemoveServerFromHostRequest, opts ...grpc.CallOption) (*RemoveServerFromHostResponse, error)
}

type hostMetadataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHostMetadataServiceClient(cc grpc.ClientConnInterface) HostMetadataServiceClient {
	return &hostMetadataServiceClient{cc}
}

func (c *hostMetadataServiceClient) CreateHostServer(ctx context.Context, in *CreateHostServerRequest, opts ...grpc.CallOption) (*CreateHostServerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateHostServerResponse)
	err := c.cc.Invoke(ctx, HostMetadataService_CreateHostServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostMetadataServiceClient) DeleteHostServer(ctx context.Context, in *DeleteHostServerRequest, opts ...grpc.CallOption) (*DeleteHostServerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteHostServerResponse)
	err := c.cc.Invoke(ctx, HostMetadataService_DeleteHostServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostMetadataServiceClient) GetAllHostServers(ctx context.Context, in *GetAllHostServersRequest, opts ...grpc.CallOption) (*GetAllHostServersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllHostServersResponse)
	err := c.cc.Invoke(ctx, HostMetadataService_GetAllHostServers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostMetadataServiceClient) AddServerToHost(ctx context.Context, in *AddServerToHostRequest, opts ...grpc.CallOption) (*AddServerToHostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddServerToHostResponse)
	err := c.cc.Invoke(ctx, HostMetadataService_AddServerToHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostMetadataServiceClient) RemoveServerFromHost(ctx context.Context, in *RemoveServerFromHostRequest, opts ...grpc.CallOption) (*RemoveServerFromHostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveServerFromHostResponse)
	err := c.cc.Invoke(ctx, HostMetadataService_RemoveServerFromHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HostMetadataServiceServer is the server API for HostMetadataService service.
// All implementations must embed UnimplementedHostMetadataServiceServer
// for forward compatibility.
type HostMetadataServiceServer interface {
	CreateHostServer(context.Context, *CreateHostServerRequest) (*CreateHostServerResponse, error)
	DeleteHostServer(context.Context, *DeleteHostServerRequest) (*DeleteHostServerResponse, error)
	GetAllHostServers(context.Context, *GetAllHostServersRequest) (*GetAllHostServersResponse, error)
	AddServerToHost(context.Context, *AddServerToHostRequest) (*AddServerToHostResponse, error)
	RemoveServerFromHost(context.Context, *RemoveServerFromHostRequest) (*RemoveServerFromHostResponse, error)
	mustEmbedUnimplementedHostMetadataServiceServer()
}

// UnimplementedHostMetadataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHostMetadataServiceServer struct{}

func (UnimplementedHostMetadataServiceServer) CreateHostServer(context.Context, *CreateHostServerRequest) (*CreateHostServerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateHostServer not implemented")
}
func (UnimplementedHostMetadataServiceServer) DeleteHostServer(context.Context, *DeleteHostServerRequest) (*DeleteHostServerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteHostServer not implemented")
}
func (UnimplementedHostMetadataServiceServer) GetAllHostServers(context.Context, *GetAllHostServersRequest) (*GetAllHostServersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllHostServers not implemented")
}
func (UnimplementedHostMetadataServiceServer) AddServerToHost(context.Context, *AddServerToHostRequest) (*AddServerToHostResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddServerToHost not implemented")
}
func (UnimplementedHostMetadataServiceServer) RemoveServerFromHost(context.Context, *RemoveServerFromHostRequest) (*RemoveServerFromHostResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveServerFromHost not implemented")
}
func (UnimplementedHostMetadataServiceServer) mustEmbedUnimplementedHostMetadataServiceServer() {}
func (UnimplementedHostMetadataServiceServer) testEmbeddedByValue()                             {}

// UnsafeHostMetadataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HostMetadataServiceServer will
// result in compilation errors.
type UnsafeHostMetadataServiceServer interface {
	mustEmbedUnimplementedHostMetadataServiceServer()
}

func RegisterHostMetadataServiceServer(s grpc.ServiceRegistrar, srv HostMetadataServiceServer) {
	// If the following call panics, it indicates UnimplementedHostMetadataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HostMetadataService_ServiceDesc, srv)
}

func _HostMetadataService_CreateHostServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateHostServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostMetadataServiceServer).CreateHostServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostMetadataService_CreateHostServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostMetadataServiceServer).CreateHostServer(ctx, req.(*CreateHostServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostMetadataService_DeleteHostServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteHostServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostMetadataServiceServer).DeleteHostServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostMetadataService_DeleteHostServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostMetadataServiceServer).DeleteHostServer(ctx, req.(*DeleteHostServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostMetadataService_GetAllHostServers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllHostServersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostMetadataServiceServer).GetAllHostServers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostMetadataService_GetAllHostServers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostMetadataServiceServer).GetAllHostServers(ctx, req.(*GetAllHostServersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostMetadataService_AddServerToHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddServerToHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostMetadataServiceServer).AddServerToHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostMetadataService_AddServerToHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostMetadataServiceServer).AddServerToHost(ctx, req.(*AddServerToHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostMetadataService_RemoveServerFromHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveServerFromHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostMetadataServiceServer).RemoveServerFromHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostMetadataService_RemoveServerFromHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostMetadataServiceServer).RemoveServerFromHost(ctx, req.(*RemoveServerFromHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HostMetadataService_ServiceDesc is the grpc.ServiceDesc for HostMetadataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HostMetadataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "host_metadata_service.HostMetadataService",
	HandlerType: (*HostMetadataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateHostServer",
			Handler:    _HostMetadataService_CreateHostServer_Handler,
		},
		{
			MethodName: "DeleteHostServer",
			Handler:    _HostMetadataService_DeleteHostServer_Handler,
		},
		{
			MethodName: "GetAllHostServers",
			Handler:    _HostMetadataService_GetAllHostServers_Handler,
		},
		{
			MethodName: "AddServerToHost",
			Handler:    _HostMetadataService_AddServerToHost_Handler,
		},
		{
			MethodName: "RemoveServerFromHost",
			Handler:    _HostMetadataService_RemoveServerFromHost_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/proto/host-metadata-service/host-metadata-service.proto",
}
