CREATE TABLE IF NOT EXISTS hosts (
    id TEXT PRIMARY KEY,
    servers TEXT[] DEFAULT ARRAY[]::TEXT[],
    ram INT NOT NULL,
    cores INT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS network (
    id TEXT PRIMARY KEY REFERENCES hosts(id) ON DELETE CASCADE,
    ip TEXT UNIQUE NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password TEXT UNIQUE NOT NULL,
    email TEXT NOT NULL,
    bundles JSONB DEFAULT '{}'::JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE bundle_keys (
    key TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    bundle TEXT NOT NULL,
    used BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT now()
);