services:
  postgres-hub:
    image: postgres:16
    container_name: postgres-hub
    restart: unless-stopped
    env_file:
      - config/docker.env
    ports:
      - "2345:5432"
    volumes:
      - postgres_data_hub:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - disknet-hub

  migrate:
    image: migrate/migrate
    container_name: migrate-hub
    depends_on:
      postgres-hub:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations:ro
    entrypoint: >
      migrate
      -path /migrations
      -database postgres://postgres:${POSTGRES_PASSWORD}@postgres-hub:5432/${POSTGRES_DB}?sslmode=disable
      up
    networks:
      - disknet-hub
  network-service:
    build: services/network-service
    container_name: network-service
    env_file:
      - config/docker.env
    ports:
      - "${NETWORK_SERVICE_HTTP_PORT}:${NETWORK_SERVICE_HTTP_PORT}"
    depends_on:
      migrate:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:${NETWORK_SERVICE_HTTP_PORT}/network-service/health"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - disknet-hub
  host-metadata-service:
    build: services/host-metadata-service
    container_name: host-metadata-service
    env_file:
      - config/docker.env
    ports:
      - "${HOST_METADATA_SERVICE_PORT}:${HOST_METADATA_SERVICE_PORT}"
    depends_on:
      migrate:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:${HOST_METADATA_SERVICE_PORT}/host-metadata-service/health"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - disknet-hub
  gateway:
    build: services/gateway
    container_name: gateway-hub
    env_file:
      - config/docker.env
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    depends_on:
      migrate:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:${GATEWAY_PORT}/gateway/health"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - disknet-hub
  task-service:
    build: services/task-service
    container_name: task-service
    env_file:
      - config/docker.env
    ports:
      - "${TASK_SERVICE_PORT}:${TASK_SERVICE_PORT}"
    depends_on:
      migrate:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:${TASK_SERVICE_PORT}/task-service/health"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - disknet-hub
  auth-service:
    build: services/auth-service
    container_name: auth-service
    env_file:
      - config/docker.env
    ports:
      - "${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}"
    depends_on:
      migrate:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:${AUTH_SERVICE_PORT}/auth-service/health"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - disknet-hub
  bundle-service:
    build: services/bundle-service
    container_name: bundle-service
    env_file:
      - config/docker.env
    ports:
      - "${BUNDLE_SERVICE_PORT}:${BUNDLE_SERVICE_PORT}"
    depends_on:
      migrate:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:${BUNDLE_SERVICE_PORT}/bundle-service/health"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - disknet-hub
  backup-service:
    build: services/backup-service
    container_name: backup-service
    env_file:
      - config/docker.env
    ports:
      - "${BACKUP_SERVICE_PORT}:${BACKUP_SERVICE_PORT}"
    depends_on:
      migrate:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "wget", "-qO-"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - disknet-hub

volumes:
  postgres_data_hub:

networks:
  disknet-hub:
    driver: bridge