// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: hub/services/task-service/internal/proto/backup-service/backup-service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BackupList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	ServerID      string                 `protobuf:"bytes,2,opt,name=ServerID,proto3" json:"ServerID,omitempty"`
	Backup        string                 `protobuf:"bytes,3,opt,name=Backup,proto3" json:"Backup,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupList) Reset() {
	*x = BackupList{}
	mi := &file_hub_services_task_service_internal_proto_backup_service_backup_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupList) ProtoMessage() {}

func (x *BackupList) ProtoReflect() protoreflect.Message {
	mi := &file_hub_services_task_service_internal_proto_backup_service_backup_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupList.ProtoReflect.Descriptor instead.
func (*BackupList) Descriptor() ([]byte, []int) {
	return file_hub_services_task_service_internal_proto_backup_service_backup_service_proto_rawDescGZIP(), []int{0}
}

func (x *BackupList) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *BackupList) GetServerID() string {
	if x != nil {
		return x.ServerID
	}
	return ""
}

func (x *BackupList) GetBackup() string {
	if x != nil {
		return x.Backup
	}
	return ""
}

type DeleteBackupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BackupID      string                 `protobuf:"bytes,1,opt,name=BackupID,proto3" json:"BackupID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBackupRequest) Reset() {
	*x = DeleteBackupRequest{}
	mi := &file_hub_services_task_service_internal_proto_backup_service_backup_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBackupRequest) ProtoMessage() {}

func (x *DeleteBackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_services_task_service_internal_proto_backup_service_backup_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBackupRequest.ProtoReflect.Descriptor instead.
func (*DeleteBackupRequest) Descriptor() ([]byte, []int) {
	return file_hub_services_task_service_internal_proto_backup_service_backup_service_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteBackupRequest) GetBackupID() string {
	if x != nil {
		return x.BackupID
	}
	return ""
}

type DeleteBackupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBackupResponse) Reset() {
	*x = DeleteBackupResponse{}
	mi := &file_hub_services_task_service_internal_proto_backup_service_backup_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBackupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBackupResponse) ProtoMessage() {}

func (x *DeleteBackupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_services_task_service_internal_proto_backup_service_backup_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBackupResponse.ProtoReflect.Descriptor instead.
func (*DeleteBackupResponse) Descriptor() ([]byte, []int) {
	return file_hub_services_task_service_internal_proto_backup_service_backup_service_proto_rawDescGZIP(), []int{2}
}

type CreateBackupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	ServerID      string                 `protobuf:"bytes,2,opt,name=ServerID,proto3" json:"ServerID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBackupRequest) Reset() {
	*x = CreateBackupRequest{}
	mi := &file_hub_services_task_service_internal_proto_backup_service_backup_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBackupRequest) ProtoMessage() {}

func (x *CreateBackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_services_task_service_internal_proto_backup_service_backup_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBackupRequest.ProtoReflect.Descriptor instead.
func (*CreateBackupRequest) Descriptor() ([]byte, []int) {
	return file_hub_services_task_service_internal_proto_backup_service_backup_service_proto_rawDescGZIP(), []int{3}
}

func (x *CreateBackupRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *CreateBackupRequest) GetServerID() string {
	if x != nil {
		return x.ServerID
	}
	return ""
}

type CreateBackupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBackupResponse) Reset() {
	*x = CreateBackupResponse{}
	mi := &file_hub_services_task_service_internal_proto_backup_service_backup_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBackupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBackupResponse) ProtoMessage() {}

func (x *CreateBackupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_services_task_service_internal_proto_backup_service_backup_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBackupResponse.ProtoReflect.Descriptor instead.
func (*CreateBackupResponse) Descriptor() ([]byte, []int) {
	return file_hub_services_task_service_internal_proto_backup_service_backup_service_proto_rawDescGZIP(), []int{4}
}

type GetBackupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerID      string                 `protobuf:"bytes,1,opt,name=ServerID,proto3" json:"ServerID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBackupRequest) Reset() {
	*x = GetBackupRequest{}
	mi := &file_hub_services_task_service_internal_proto_backup_service_backup_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBackupRequest) ProtoMessage() {}

func (x *GetBackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_services_task_service_internal_proto_backup_service_backup_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBackupRequest.ProtoReflect.Descriptor instead.
func (*GetBackupRequest) Descriptor() ([]byte, []int) {
	return file_hub_services_task_service_internal_proto_backup_service_backup_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetBackupRequest) GetServerID() string {
	if x != nil {
		return x.ServerID
	}
	return ""
}

type GetBackupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Backups       []*BackupList          `protobuf:"bytes,1,rep,name=backups,proto3" json:"backups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBackupResponse) Reset() {
	*x = GetBackupResponse{}
	mi := &file_hub_services_task_service_internal_proto_backup_service_backup_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBackupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBackupResponse) ProtoMessage() {}

func (x *GetBackupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_services_task_service_internal_proto_backup_service_backup_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBackupResponse.ProtoReflect.Descriptor instead.
func (*GetBackupResponse) Descriptor() ([]byte, []int) {
	return file_hub_services_task_service_internal_proto_backup_service_backup_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetBackupResponse) GetBackups() []*BackupList {
	if x != nil {
		return x.Backups
	}
	return nil
}

var File_hub_services_task_service_internal_proto_backup_service_backup_service_proto protoreflect.FileDescriptor

const file_hub_services_task_service_internal_proto_backup_service_backup_service_proto_rawDesc = "" +
	"\n" +
	"Lhub/services/task-service/internal/proto/backup-service/backup-service.proto\x12\x0ebackup_service\"X\n" +
	"\n" +
	"BackupList\x12\x16\n" +
	"\x06UserID\x18\x01 \x01(\tR\x06UserID\x12\x1a\n" +
	"\bServerID\x18\x02 \x01(\tR\bServerID\x12\x16\n" +
	"\x06Backup\x18\x03 \x01(\tR\x06Backup\"1\n" +
	"\x13DeleteBackupRequest\x12\x1a\n" +
	"\bBackupID\x18\x01 \x01(\tR\bBackupID\"\x16\n" +
	"\x14DeleteBackupResponse\"I\n" +
	"\x13CreateBackupRequest\x12\x16\n" +
	"\x06UserID\x18\x01 \x01(\tR\x06UserID\x12\x1a\n" +
	"\bServerID\x18\x02 \x01(\tR\bServerID\"\x16\n" +
	"\x14CreateBackupResponse\".\n" +
	"\x10GetBackupRequest\x12\x1a\n" +
	"\bServerID\x18\x01 \x01(\tR\bServerID\"I\n" +
	"\x11GetBackupResponse\x124\n" +
	"\abackups\x18\x01 \x03(\v2\x1a.backup_service.BackupListR\abackups2\x97\x02\n" +
	"\rBackupService\x12Y\n" +
	"\fCreateBackup\x12#.backup_service.CreateBackupRequest\x1a$.backup_service.CreateBackupResponse\x12Y\n" +
	"\fDeleteBackup\x12#.backup_service.DeleteBackupRequest\x1a$.backup_service.DeleteBackupResponse\x12P\n" +
	"\tGetBackup\x12 .backup_service.GetBackupRequest\x1a!.backup_service.GetBackupResponseB\x17Z\x15/internal/proto;protob\x06proto3"

var (
	file_hub_services_task_service_internal_proto_backup_service_backup_service_proto_rawDescOnce sync.Once
	file_hub_services_task_service_internal_proto_backup_service_backup_service_proto_rawDescData []byte
)

func file_hub_services_task_service_internal_proto_backup_service_backup_service_proto_rawDescGZIP() []byte {
	file_hub_services_task_service_internal_proto_backup_service_backup_service_proto_rawDescOnce.Do(func() {
		file_hub_services_task_service_internal_proto_backup_service_backup_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hub_services_task_service_internal_proto_backup_service_backup_service_proto_rawDesc), len(file_hub_services_task_service_internal_proto_backup_service_backup_service_proto_rawDesc)))
	})
	return file_hub_services_task_service_internal_proto_backup_service_backup_service_proto_rawDescData
}

var file_hub_services_task_service_internal_proto_backup_service_backup_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_hub_services_task_service_internal_proto_backup_service_backup_service_proto_goTypes = []any{
	(*BackupList)(nil),           // 0: backup_service.BackupList
	(*DeleteBackupRequest)(nil),  // 1: backup_service.DeleteBackupRequest
	(*DeleteBackupResponse)(nil), // 2: backup_service.DeleteBackupResponse
	(*CreateBackupRequest)(nil),  // 3: backup_service.CreateBackupRequest
	(*CreateBackupResponse)(nil), // 4: backup_service.CreateBackupResponse
	(*GetBackupRequest)(nil),     // 5: backup_service.GetBackupRequest
	(*GetBackupResponse)(nil),    // 6: backup_service.GetBackupResponse
}
var file_hub_services_task_service_internal_proto_backup_service_backup_service_proto_depIdxs = []int32{
	0, // 0: backup_service.GetBackupResponse.backups:type_name -> backup_service.BackupList
	3, // 1: backup_service.BackupService.CreateBackup:input_type -> backup_service.CreateBackupRequest
	1, // 2: backup_service.BackupService.DeleteBackup:input_type -> backup_service.DeleteBackupRequest
	5, // 3: backup_service.BackupService.GetBackup:input_type -> backup_service.GetBackupRequest
	4, // 4: backup_service.BackupService.CreateBackup:output_type -> backup_service.CreateBackupResponse
	2, // 5: backup_service.BackupService.DeleteBackup:output_type -> backup_service.DeleteBackupResponse
	6, // 6: backup_service.BackupService.GetBackup:output_type -> backup_service.GetBackupResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_hub_services_task_service_internal_proto_backup_service_backup_service_proto_init() }
func file_hub_services_task_service_internal_proto_backup_service_backup_service_proto_init() {
	if File_hub_services_task_service_internal_proto_backup_service_backup_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hub_services_task_service_internal_proto_backup_service_backup_service_proto_rawDesc), len(file_hub_services_task_service_internal_proto_backup_service_backup_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hub_services_task_service_internal_proto_backup_service_backup_service_proto_goTypes,
		DependencyIndexes: file_hub_services_task_service_internal_proto_backup_service_backup_service_proto_depIdxs,
		MessageInfos:      file_hub_services_task_service_internal_proto_backup_service_backup_service_proto_msgTypes,
	}.Build()
	File_hub_services_task_service_internal_proto_backup_service_backup_service_proto = out.File
	file_hub_services_task_service_internal_proto_backup_service_backup_service_proto_goTypes = nil
	file_hub_services_task_service_internal_proto_backup_service_backup_service_proto_depIdxs = nil
}
